(function(){const K="jt1:",S={get(k,d){try{const v=localStorage.getItem(K+k);return v?JSON.parse(v):d}catch(e){return d}},set(k,v){try{localStorage.setItem(K+k,JSON.stringify(v))}catch(e){}}};
const JT=window.JT={S,cfg:null},$=(s,r=document)=>r.querySelector(s);
document.documentElement.dataset.theme=S.get("theme","dark");
document.addEventListener("click",e=>{const b=e.target.closest("[data-theme-toggle]");if(!b)return;const n=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=n;S.set("theme",n)});
JT.toast=(m,t="ok")=>{let h=$("#toasts");if(!h){h=document.createElement("div");h.id="toasts";h.setAttribute("role","status");h.setAttribute("aria-live","polite");document.body.append(h)}const d=document.createElement("div");d.className="toast "+t;d.textContent=m;h.append(d);setTimeout(()=>d.remove(),2600)};
JT.Analytics={track(n,p){if(!JT.cfg||!JT.cfg.analytics.enabled)return;try{(JT.Analytics.provider||(()=>{}))(n,p)}catch(e){}}};
JT.Consent={state:()=>(JT.cfg&&JT.cfg.consent)||"unknown"};
JT.AdManager={last:0,count:0,busy:false,provider:null,
async onSuccess(id,tool){try{const c=JT.cfg&&JT.cfg.ads;if(!c||!c.enabled||!c.postActionEnabled||tool.adAfterUse===false)return;
if(!["granted","not-required"].includes(JT.Consent.state()))return;
const cd=tool.adCooldownMs||c.defaultCooldownMs,max=tool.maxAdsPerSession||c.maxAdsPerSession,now=Date.now();
if(this.busy||this.count>=max||now-this.last<cd)return;this.busy=true;
JT.Analytics.track("ad_request",{tool:id});const slot=$("#ad-post-action");if(!slot)return;
if(c.mode==="test"){slot.hidden=false;slot.textContent="";const l=document.createElement("small");l.textContent="Advertisement (test mode)";const x=document.createElement("button");x.className="btn ghost";x.textContent="Close ad";x.onclick=()=>{slot.hidden=true};slot.append(l,x)}
else if(this.provider){await this.provider(slot)}else return;
this.last=now;this.count++;JT.Analytics.track("ad_displayed",{tool:id})}catch(e){JT.Analytics.track("ad_failed",{tool:id})}finally{this.busy=false}}};
JT.fav={list:()=>S.get("fav",[]),toggle(id){let l=this.list();l=l.includes(id)?l.filter(x=>x!==id):[...l,id];S.set("fav",l);return l.includes(id)}};
JT.recent=id=>{let l=S.get("recent",[]).filter(x=>x.id!==id);l.unshift({id,t:Date.now()});S.set("recent",l.slice(0,8))};
JT.download=(text,name,mime="text/plain")=>{const u=URL.createObjectURL(new Blob([text],{type:mime}));const a=document.createElement("a");a.href=u;a.download="jadon-tools-"+name.replace(/[^\w.-]/g,"_");document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)};
JT.copy=async t=>{try{await navigator.clipboard.writeText(t);JT.toast("Copied")}catch(e){JT.toast("Copy failed. Select the text and copy manually.","err")}};
JT.share=async()=>{try{if(navigator.share)await navigator.share({title:document.title,url:location.href});else await JT.copy(location.href)}catch(e){}};
addEventListener("error",()=>JT.Analytics.track("tool_error",{msg:"js"}));
addEventListener("unhandledrejection",()=>JT.Analytics.track("tool_error",{msg:"promise"}));
const ready=fetch(document.documentElement.dataset.root+"data/config.json").then(r=>r.json()).then(c=>{JT.cfg=c;if(JT.Magic)JT.Magic.refresh();if(c.featureFlags.pwa&&"serviceWorker"in navigator)navigator.serviceWorker.register(document.documentElement.dataset.root+"sw.js").catch(()=>{})}).catch(()=>{});
const paint=b=>{const on=JT.fav.list().includes(b.dataset.fav);b.setAttribute("aria-pressed",on);b.textContent=on?"★":"☆"};
document.querySelectorAll("[data-fav]").forEach(paint);
document.addEventListener("click",e=>{const b=e.target.closest("[data-fav]");if(!b)return;e.preventDefault();JT.fav.toggle(b.dataset.fav);paint(b)});
const q=$("#q");if(q){const f=()=>{const v=q.value.toLowerCase().trim();let n=0;document.querySelectorAll(".card").forEach(c=>{const m=(!v||c.dataset.s.includes(v))&&(!JT.cat||!c.closest("#all-grid")||c.dataset.cat===JT.cat);c.hidden=!m;if(m)n++});const e=$("#empty");if(e)e.hidden=n>0};q.addEventListener("input",f);const p=new URLSearchParams(location.search).get("q");if(p){q.value=p;f()}}
JT.urls=[];JT.clearResult=()=>{JT.urls.forEach(u=>URL.revokeObjectURL(u));JT.urls=[];const f=$("#files");if(f)f.textContent="";const d=$("#dl");if(d)d.hidden=false;const p=$("#preview");if(p&&!p.hidden&&!JT_TOOLS[$("#tool").dataset.id].preview)p.hidden=true};
JT.result=r=>{JT.clearResult();if(!(r&&typeof r==="object"))return r;const box=$("#files");(r.files||[]).forEach((f,k)=>{const u=URL.createObjectURL(f.blob);JT.urls.push(u);if(k===0&&/^image\//.test(f.type)){const im=document.createElement("img");im.src=u;im.alt="Result preview";box.append(im)}const a=document.createElement("a");a.className="btn pri";a.href=u;a.download=f.name;a.textContent="Download "+f.name.replace("jadon-tools-","");a.addEventListener("click",()=>JT.Analytics.track("tool_download",{tool:$("#tool").dataset.id}));box.append(a)});if(r.print&&(r.files||[])[0]){const pb=document.createElement("button");pb.type="button";pb.className="btn";pb.textContent="Print";pb.onclick=()=>{const f=document.createElement("iframe");f.style.cssText="position:fixed;width:0;height:0;border:0";f.srcdoc='<img src="'+JT.urls[0]+'" style="max-width:100%" onload="setTimeout(function(){print()},50)">';document.body.append(f);setTimeout(()=>f.remove(),60000)};box.append(pb)}if((r.files||[]).length)$("#dl").hidden=true;return r.text||""};
addEventListener("pagehide",()=>JT.clearResult&&JT.clearResult());
JT._l={};JT.lib1=u=>JT._l[u]||(JT._l[u]=new Promise((ok,no)=>{const s=document.createElement("script");s.src=u;const to=setTimeout(()=>{delete JT._l[u];no("A required component took too long to load. Check your internet connection and try again.")},20000);s.onload=()=>{clearTimeout(to);ok()};s.onerror=()=>{clearTimeout(to);delete JT._l[u];no("Could not load a required component. Check your internet connection and try again.")};document.head.append(s)}));
JT.lib=async u=>{let e;for(const x of[].concat(u)){try{return await JT.lib1(x)}catch(er){e=er}}throw e};
JT.media={streams:new Set(),async start(c){const m=navigator.mediaDevices;if(!m||!m[c.screen?"getDisplayMedia":"getUserMedia"])throw"This feature is not supported by your browser.";try{const s=await(c.screen?m.getDisplayMedia(c.opts):m.getUserMedia(c.opts));this.streams.add(s);return s}catch(e){const n=e&&e.name;throw n==="NotAllowedError"||n==="SecurityError"?"Permission was denied. Allow access in your browser's site settings and try again.":n==="NotFoundError"||n==="OverconstrainedError"?"No matching device was found.":n==="NotReadableError"?"The device is being used by another app.":"Could not start the device."}},stop(s){if(!s)return;s.getTracks().forEach(t=>t.stop());this.streams.delete(s)},stopAll(){this.streams.forEach(s=>s.getTracks().forEach(t=>t.stop()));this.streams.clear()}};
addEventListener("pagehide",()=>JT.media.stopAll());
const mb=$("#menu-btn"),mn=$("#menu");if(mb){mb.onclick=()=>{const o=mn.classList.toggle("open");mb.setAttribute("aria-expanded",o);document.body.style.overflow=o?"hidden":""};mn.addEventListener("click",e=>{if(e.target.closest("a")){mn.classList.remove("open");document.body.style.overflow="";mb.setAttribute("aria-expanded",false)}});addEventListener("keydown",e=>{if(e.key==="Escape")mn.classList.remove("open")})}
addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();const s=$("#q");s?s.focus():location.href=document.documentElement.dataset.root+"search/"}});
const ch=$("#chips");if(ch)ch.addEventListener("click",e=>{const b=e.target.closest(".chip");if(!b)return;ch.querySelectorAll(".chip").forEach(x=>x.classList.toggle("on",x===b));JT.cat=b.dataset.cat;q.dispatchEvent(new Event("input"))});
const renderHome=()=>{const all=$("#all-grid");if(!all)return;const fill=(box,ids)=>{box.textContent="";ids.forEach(id=>{const c=all.querySelector('.card[data-id="'+id+'"]');if(c){const n=c.cloneNode(true);n.hidden=false;box.append(n);paint(n.querySelector("[data-fav]"))}})};
const rc=S.get("recent",[]).map(x=>x.id),fv=JT.fav.list();fill($("#recent-list"),rc.slice(0,4));$("#recent").hidden=!rc.length;fill($("#fav-list"),fv);$("#fav-empty").hidden=fv.length>0};
renderHome();document.addEventListener("click",e=>{if(e.target.closest("[data-fav]"))setTimeout(renderHome,0)});

const page=$("#tool");if(page){const id=page.dataset.id,T=JT_TOOLS[id],meta=JSON.parse(page.dataset.meta),form=$("#form"),out=$("#out"),err=$("#err");JT.recent(id);if(T.mount){page.classList.add("live");const cl=T.mount(form,JT);addEventListener("pagehide",()=>cl&&cl());return}
T.fields.forEach(f=>{const w=document.createElement("label");w.textContent=f.label;let i;if(f.type==="textarea"){i=document.createElement("textarea");i.rows=8}else if(f.type==="file"){i=document.createElement("input");i.type="file";if(f.accept)i.accept=f.accept;if(f.multi)i.multiple=true}else if(f.type==="select"){i=document.createElement("select");f.opts.forEach(o=>{const e=document.createElement("option");e.textContent=o;i.append(e)})}else{i=document.createElement("input");i.type=f.type;if(f.type==="number")i.step="any"}i.id="f_"+f.id;if(f.hint){const s2=document.createElement("small");s2.className="hint";s2.textContent=f.hint;w.append(s2)}if(f.type==="checkbox"){i.checked=!!f.def;w.className="chk";w.prepend(i)}else{if(f.def!==undefined)i.value=f.def;w.append(i)}if(f.when)w.dataset.when=JSON.stringify(f.when);form.append(w)});const sync=()=>form.querySelectorAll("[data-when]").forEach(w=>{const c=JSON.parse(w.dataset.when),e=$("#f_"+c.id);w.hidden=!(e&&c.in.includes(e.value))});form.addEventListener("input",sync);sync();
$("#run").onclick=async()=>{err.hidden=true;const rb=$("#run");if(rb.disabled)return;rb.disabled=true;rb.textContent="Working…";const v={};T.fields.forEach(f=>{const i=$("#f_"+f.id);v[f.id]=f.type==="checkbox"?i.checked:f.type==="file"?[...i.files]:i.value});
try{out.value=JT.result(await(JT.Magic?JT.Magic.run(id,meta.cat,()=>T.run(v)):T.run(v)));if(T.preview){const pv=$("#preview");pv.hidden=false;T.preview(v,pv)}$("#acts").hidden=false;JT.toast("Done");JT.Analytics.track("tool_success",{tool:id});JT.AdManager.onSuccess(id,meta)}catch(e){if(e==="__locked__")return;JT.clearResult();err.textContent=typeof e==="string"?e:"Something went wrong. Please check your input and try again.";err.hidden=false;$("#acts").hidden=true;out.value="";JT.Analytics.track("tool_error",{tool:id})}finally{rb.disabled=false;rb.textContent="Run"}};
$("#reset").onclick=()=>{setTimeout(sync,0);JT.clearResult();T.fields.forEach(f=>{const i=$("#f_"+f.id);if(f.type==="checkbox")i.checked=!!f.def;else i.value=f.def!==undefined?f.def:""});out.value="";err.hidden=true;$("#acts").hidden=true;const s=$("#ad-post-action");if(s)s.hidden=true};
$("#copy").onclick=()=>JT.copy(out.value);$("#dl").onclick=()=>JT.download(out.value,id+".txt");$("#share").onclick=JT.share}


(()=>{const fi=()=>document.querySelector("#tool #form input[type=file]"),put=fs=>{const i=fi();if(!i||!fs.length)return false;const dt=new DataTransfer();(i.multiple?[...i.files,...fs]:[fs[0]]).forEach(f=>dt.items.add(f));i.files=dt.files;i.dispatchEvent(new Event("change",{bubbles:true}));return true};
document.addEventListener("paste",e=>{const f=e.clipboardData&&[...e.clipboardData.files];if(f&&f.length&&put(f)){e.preventDefault();JT.toast("File pasted")}});
document.addEventListener("dragover",e=>{if(fi()&&e.dataTransfer&&[...e.dataTransfer.types].includes("Files"))e.preventDefault()});
document.addEventListener("drop",e=>{if(fi()&&e.dataTransfer&&e.dataTransfer.files.length){e.preventDefault();if(put([...e.dataTransfer.files]))JT.toast("File added")}})})();
})();
