(function(){
if(!window.JT)return;
const $=(s,r=document)=>r.querySelector(s),pick=a=>a[Math.random()*a.length|0],RM=()=>matchMedia("(prefers-reduced-motion: reduce)").matches;
const html=(c,h)=>{const e=document.createElement("div");e.className=c;e.innerHTML=h;return e}; // h is only static SVG/text built here, never user input
// ---------- 14 original mascots, drawn from simple shapes ----------
const CH=[["Pixa","#06d6ff","#2563ff","visor"],["Nova","#c084fc","#7c3aed","halo"],["Bolt","#fbbf24","#f59e0b","antenna"],["Mimi","#f472b6","#ec4899","bow"],["Zed","#34d399","#059669","hat"],["Orbi","#60a5fa","#2563eb","ring"],["Glim","#a3e635","#65a30d","leaf"],["Koda","#fb923c","#ea580c","horn"],["Pip","#e879f9","#a21caf","wing"],["Tess","#22d3ee","#0891b2","goggles"],["Ruko","#f87171","#dc2626","mask"],["Luma","#fde047","#ca8a04","star"],["Echo","#94a3b8","#475569","dish"],["Yuzu","#fcd34d","#d97706","crown"]];
const ACC={visor:'<rect x="14" y="22" width="36" height="9" rx="4" fill="#0b1220" opacity=".85"/>',halo:'<ellipse cx="32" cy="8" rx="12" ry="3.5" fill="none" stroke="#fde047" stroke-width="2.5"/>',antenna:'<path d="M32 14V4" stroke="#fff" stroke-width="2"/><circle cx="32" cy="4" r="3" fill="#fde047"/>',bow:'<path d="M32 14l-9-5v10zM32 14l9-5v10z" fill="#fff"/>',hat:'<path d="M18 16h28l-6-12H24z" fill="#1e293b"/>',ring:'<ellipse cx="32" cy="34" rx="28" ry="6" fill="none" stroke="#fff" stroke-width="2" opacity=".7"/>',leaf:'<path d="M32 14c-8-2-10-8-8-10 6 0 10 4 8 10zM32 14c8-2 10-8 8-10-6 0-10 4-8 10z" fill="#bef264"/>',horn:'<path d="M20 16l-4-12 10 7zM44 16l4-12-10 7z" fill="#fff"/>',wing:'<path d="M10 30c-8-8-4-16 4-14zM54 30c8-8 4-16-4-14z" fill="#fff" opacity=".85"/>',goggles:'<circle cx="24" cy="30" r="7" fill="none" stroke="#fff" stroke-width="2.5"/><circle cx="40" cy="30" r="7" fill="none" stroke="#fff" stroke-width="2.5"/>',mask:'<path d="M14 26h36v6H14z" fill="#111827"/>',star:'<path d="M32 2l2.5 6 6.5.5-5 4 1.8 6.5L32 16l-5.8 3 1.8-6.5-5-4 6.5-.5z" fill="#fff"/>',dish:'<path d="M24 14q8-10 16 0z" fill="#e2e8f0"/><path d="M32 14V8" stroke="#e2e8f0" stroke-width="2"/>',crown:'<path d="M20 16l2-10 6 6 4-8 4 8 6-6 2 10z" fill="#fde047"/>'};
const mascot=([n,a,b,k],i)=>`<svg viewBox="0 0 64 64" width="56" height="56" role="img" aria-label="${n}, a small Jadon mascot"><defs><linearGradient id="mg${i}" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient></defs><rect x="14" y="14" width="36" height="34" rx="${i%3?14:8}" fill="url(#mg${i})"/>${ACC[k]}<circle cx="25" cy="31" r="3.4" fill="#fff"/><circle cx="39" cy="31" r="3.4" fill="#fff"/><circle cx="26" cy="31.5" r="1.7" fill="#0b1220"/><circle cx="40" cy="31.5" r="1.7" fill="#0b1220"/><path d="M27 39q5 4 10 0" stroke="#0b1220" stroke-width="2" fill="none" stroke-linecap="round"/><rect x="22" y="48" width="20" height="10" rx="5" fill="${b}"/></svg>`;
// ---------- 12 original monsters ----------
const MON=[["Glitchfang","#ef4444","#7f1d1d",3,"horns"],["Voidling","#8b5cf6","#312e81",1,"tent"],["Byteworm","#22c55e","#14532d",4,"spikes"],["Pixelmaw","#f97316","#7c2d12",2,"horns"],["Firewall Fiend","#f43f5e","#881337",2,"spikes"],["Shadow Node","#64748b","#0f172a",3,"tent"],["Crystalbeast","#22d3ee","#164e63",2,"spikes"],["Null Pointer","#a3a3a3","#262626",1,"horns"],["Stack Overflow","#fbbf24","#78350f",5,"tent"],["Malware Moth","#e879f9","#701a75",2,"wings"],["Packet Drake","#34d399","#064e3b",2,"horns"],["Kernel Panic","#fb7185","#4c0519",3,"spikes"]];
const FT={horns:b=>`<path d="M30 40L18 10l30 20zM90 40l12-30-30 20z" fill="${b}"/>`,spikes:b=>`<path d="M26 40l6-18 8 14 8-20 8 20 8-20 8 20 8-14 6 18z" fill="${b}"/>`,tent:b=>`<path d="M28 100q-8 12 0 20M48 104q-6 12 2 18M72 104q6 12-2 18M92 100q8 12 0 20" stroke="${b}" stroke-width="7" fill="none" stroke-linecap="round"/>`,wings:b=>`<path d="M20 70L-6 38l12 44zM100 70l26-32-12 44z" fill="${b}" opacity=".9"/>`};
const monster=([n,a,b,e,f],i)=>{let eyes="";for(let k=0;k<e;k++){const x=60+(k-(e-1)/2)*(e>3?15:22),y=62-(e>3&&k%2?10:0),r=e>3?6:8;eyes+=`<circle cx="${x}" cy="${y}" r="${r}" fill="#fff"/><circle cx="${x}" cy="${y}" r="${r/2.4}" fill="#ef4444"/>`}return`<svg viewBox="-10 -5 140 135" width="170" height="170" role="img" aria-label="${n}, a made-up monster"><defs><linearGradient id="mo${i}" x1="0" y1="0" x2="0" y2="1"><stop stop-color="${a}"/><stop offset="1" stop-color="${b}"/></linearGradient></defs>${FT[f](b)}<path d="M18 100Q8 40 60 24Q112 40 102 100Q60 114 18 100Z" fill="url(#mo${i})"/>${eyes}<path d="M34 86l8 10 8-10 8 10 8-10 8 10 8-10 8 10" stroke="#fff" stroke-width="3" fill="none" stroke-linejoin="round"/></svg>`};
// ---------- 8 genuinely different animation scenes ----------
const SYM={"text-tools":"AaBbCcXx","calculators":"+-×÷=%π√","developer-tools":"{}</>();[]","design-tools":"●●●●●","pdf-tools":"▭▭▭▭","image-tools":"■■■■■","security-tools":"01#*01","converters":"⇄→=≈⇄","utilities":"◷●◷●","business-tools":"$%#$%"};
const PREF={"text-tools":["assemble","stream","circle"],"calculators":["rings","circle","burst"],"developer-tools":["stream","beam","portal"],"design-tools":["burst","pixels","rings"],"pdf-tools":["assemble","portal","beam"],"image-tools":["pixels","assemble","burst"],"security-tools":["stream","rings","beam"],"converters":["portal","rings","circle"],"utilities":["circle","burst","portal"],"business-tools":["assemble","beam","rings"]};
const ease=t=>t<.5?2*t*t:1-Math.pow(-2*t+2,2)/2,TAU=6.283;
const SC={
circle:(c,t,w,h,p)=>{const x=w/2,y=h/2,k=Math.min(1,t*1.6);c.strokeStyle="#06d6ff";c.lineWidth=2;c.beginPath();c.arc(x,y,62,0,TAU*k);c.stroke();c.save();c.translate(x,y);c.rotate(t*5);c.font="16px monospace";p.forEach(q=>{c.fillStyle=`hsla(${q.h},90%,70%,${k})`;c.fillText(q.ch,Math.cos(q.a)*48*k-5,Math.sin(q.a)*48*k+5)});c.restore();if(t>.8){c.fillStyle=`rgba(6,214,255,${(t-.8)*3})`;c.beginPath();c.arc(x,y,20,0,TAU);c.fill()}},
portal:(c,t,w,h,p)=>{const x=w/2,y=h/2,k=Math.min(1,t*2);for(let i=0;i<4;i++){c.strokeStyle=`hsla(${260+i*20},90%,65%,${.8-i*.15})`;c.lineWidth=3;c.beginPath();c.ellipse(x,y,(18+i*10)*k,(34+i*12)*k,t*3,0,TAU);c.stroke()}c.font="14px monospace";p.forEach(q=>{const u=Math.max(0,t-.2)/.8;c.fillStyle=`hsla(${q.h},90%,70%,${1-u})`;c.fillText(q.ch,x+Math.cos(q.a)*q.r*(1-u),y+Math.sin(q.a)*q.r*.6*(1-u))})},
assemble:(c,t,w,h,p)=>{const k=ease(t);c.font="18px monospace";p.forEach((q,i)=>{const tx=w/2-60+(i%6)*24,ty=h/2-60+((i/6)|0)*20,sx=w/2+Math.cos(q.a)*q.r*1.6,sy=h/2+Math.sin(q.a)*q.r;c.fillStyle=`hsl(${q.h},85%,68%)`;c.fillText(q.ch,sx+(tx-sx)*k,sy+(ty-sy)*k)})},
beam:(c,t,w,h,p)=>{const x=w/2,k=Math.min(1,t*2),g=c.createLinearGradient(0,0,0,h);g.addColorStop(0,"rgba(6,214,255,0)");g.addColorStop(1,"rgba(6,214,255,.9)");c.fillStyle=g;c.fillRect(x-6-4*Math.sin(t*30),0,12+8*Math.sin(t*30),h*k);p.forEach(q=>{c.fillStyle=`hsla(${q.h},90%,70%,${1-t})`;c.fillRect(x+Math.cos(q.a)*q.r*t,h*k-Math.abs(Math.sin(q.a))*q.r*t*.6,3,3)})},
rings:(c,t,w,h)=>{const s=t<.7?1:1-(t-.7)/.3*.9;for(let i=0;i<3;i++){c.strokeStyle=`hsl(${190+i*40},90%,65%)`;c.lineWidth=3;c.beginPath();c.ellipse(w/2,h/2,60*s,20*s,t*6+i*1.05,0,TAU);c.stroke()}},
stream:(c,t,w,h,p)=>{c.font="14px monospace";p.forEach((q,i)=>{const col=w/2-90+i*(180/p.length),y=((t*1.4+q.s)%1)*h,cx=col+(w/2-col)*ease(t);c.fillStyle=`hsla(${q.h},90%,70%,${.9-t*.5})`;c.fillText(q.ch,cx,y)})},
burst:(c,t,w,h,p)=>{const x=w/2,y=h/2,k=t<.5?t*2:1;p.forEach(q=>{const r=q.r*k*(t<.5?1:1-(t-.5)*1.6);c.fillStyle=`hsla(${q.h},95%,65%,${1-Math.abs(t-.5)})`;c.beginPath();c.arc(x+Math.cos(q.a)*r,y+Math.sin(q.a)*r,3,0,TAU);c.fill()});if(t>.6){c.fillStyle=`rgba(255,255,255,${Math.sin((t-.6)/.4*Math.PI)*.5})`;c.beginPath();c.arc(x,y,40,0,TAU);c.fill()}},
pixels:(c,t,w,h,p)=>{const k=t<.4?t/.4:1-(t-.4)/.6;p.forEach((q,i)=>{const gx=w/2-64+(i%8)*16,gy=h/2-40+((i/8)|0)*16;c.fillStyle=`hsl(${q.h},85%,62%)`;c.fillRect(gx+Math.cos(q.a)*q.r*k,gy+Math.sin(q.a)*q.r*k,10,10)})}};
let lastC=-1,lastS="";
const start=cat=>{let ci;do ci=Math.random()*CH.length|0;while(ci===lastC);lastC=ci;const pf=(PREF[cat]||Object.keys(SC)).filter(x=>x!==lastS),scene=pick(pf.length?pf:Object.keys(SC));lastS=scene;
const o=html("magic",`<canvas width="320" height="180"></canvas><div class="mc">${mascot(CH[ci],ci)}</div><small>Creating…</small>`);o.setAttribute("role","status");document.body.append(o);const cv=$("canvas",o),c=cv.getContext("2d"),sy=SYM[cat]||"●",P=Array.from({length:40},(_,i)=>({a:Math.random()*TAU,r:40+Math.random()*90,s:Math.random(),ch:sy.charAt(i%sy.length),h:Math.random()*360})),t0=performance.now();let raf=0;const frame=()=>{const t=Math.min(1,(performance.now()-t0)/1400);c.clearRect(0,0,320,180);SC[scene](c,t,320,180,P);raf=requestAnimationFrame(frame)};frame();return()=>{cancelAnimationFrame(raf);o.classList.add("out");setTimeout(()=>o.remove(),220)}};
// ---------- usage (browser storage only; no backend) ----------
const cfg=()=>Object.assign({enabled:true,freeUses:2,sharesToUnlock:5,bonusUses:5},JT.cfg&&JT.cfg.usage),st=id=>Object.assign({n:0,b:0,s:0},JT.S.get("use:"+id,{})),sv=(id,s)=>JT.S.set("use:"+id,s);
const Usage={ok:id=>{const c=cfg();return!c.enabled||st(id).n<c.freeUses+st(id).b},hit:id=>{const s=st(id);s.n++;sv(id,s);label(id)},left:id=>{const c=cfg(),s=st(id);return Math.max(0,c.freeUses+s.b-s.n)}};
const label=id=>{const r=$("#run");if(!r)return;let p=$("#uses");if(!p){p=document.createElement("p");p.id="uses";p.className="hint";(r.closest(".row")||r.parentNode).after(p)}p.textContent=cfg().enabled?`Free uses left for this tool: ${Usage.left(id)}`:""};
// ---------- monster lock (visual effect inside the page only) ----------
const ENTR=["from-left","from-right","from-top","portal","glitch","rise"];
const crack=cv=>{cv.width=innerWidth;cv.height=innerHeight;const c=cv.getContext("2d"),x=innerWidth*(.3+Math.random()*.4),y=innerHeight*(.3+Math.random()*.4),L=[];for(let a=0;a<14;a++){let g=a/14*TAU+Math.random()*.3,px=x,py=y;const s=[];for(let k=0;k<9;k++){const l=30+Math.random()*60;g+=(Math.random()-.5)*.5;px+=Math.cos(g)*l;py+=Math.sin(g)*l;s.push([px,py])}L.push(s)}const t0=performance.now();const d=()=>{const k=Math.min(1,(performance.now()-t0)/650);c.clearRect(0,0,cv.width,cv.height);c.strokeStyle="rgba(255,255,255,.75)";c.lineWidth=1.5;L.forEach(s=>{c.beginPath();c.moveTo(x,y);s.slice(0,Math.ceil(s.length*k)).forEach(p=>c.lineTo(p[0],p[1]));c.stroke()});c.strokeStyle="rgba(255,255,255,.3)";for(let r=1;r<=4;r++){c.beginPath();c.arc(x,y,r*45*k,0,TAU);c.stroke()}if(k<1&&cv.isConnected)requestAnimationFrame(d)};d()};
const Lock={show(id){if($(".lock"))return;const c=cfg(),i=Math.random()*MON.length|0,prev=document.activeElement,o=html("lock"+(RM()?"":" shake"),`<canvas class="crack"></canvas><div class="mon ${RM()?"":pick(ENTR)}">${monster(MON[i],i)}</div><div class="lp"><h2>Free uses finished</h2><p>The free uses for this tool are used up on this device. Share Jadon Tools ${c.sharesToUnlock} times to unlock ${c.bonusUses} more uses.</p><p class="hint" id="lk-p"></p><div class="row" style="justify-content:center"><button class="btn pri" id="lk-s" type="button">${navigator.share?"Share to unlock":"Copy link (counts as a share)"}</button><button class="btn" id="lk-c" type="button">Close</button></div><small class="hint">This is only a visual effect inside this page. Your screen and device are not affected. Shares are counted on this device only; we cannot verify who opens the link.</small></div>`);o.setAttribute("role","dialog");o.setAttribute("aria-modal","true");o.setAttribute("aria-label","Free uses finished");document.body.append(o);if(!RM())crack($(".crack",o));
const prog=()=>{$("#lk-p",o).textContent=`Shares counted: ${st(id).s} of ${c.sharesToUnlock}`};prog();const close=()=>{o.remove();removeEventListener("keydown",esc);prev&&prev.focus&&prev.focus()},esc=e=>{if(e.key==="Escape")close()};addEventListener("keydown",esc);$("#lk-c",o).onclick=close;const sb=$("#lk-s",o);sb.focus();let busy=false;
sb.onclick=async()=>{if(busy)return;busy=true;let ok=false;try{const url=location.href.split("#")[0];if(navigator.share){await navigator.share({title:document.title,text:"Free online tools on Jadon Tools",url});ok=true}else{await navigator.clipboard.writeText(url);ok=true;JT.toast("Link copied")}}catch(e){}
if(ok){JT.Analytics.track("tool_share",{tool:id});const s=st(id);s.s++;if(s.s>=c.sharesToUnlock){s.s=0;s.b+=c.bonusUses;sv(id,s);o.classList.add("unlock");JT.toast(`Unlocked ${c.bonusUses} more uses`);label(id);setTimeout(close,RM()?0:900)}else{sv(id,s);prog()}}setTimeout(()=>busy=false,1500)}}};
const reveal=()=>["#out","#files"].forEach(s=>{const e=$(s);if(e){e.classList.remove("reveal");void e.offsetWidth;e.classList.add("reveal")}});
const Magic={async run(id,cat,work){if(!Usage.ok(id)){Lock.show(id);throw"__locked__"}const stop=RM()?null:start(cat);try{const[r]=await Promise.all([work(),stop?new Promise(s=>setTimeout(s,1400)):null]);Usage.hit(id);reveal();return r}finally{stop&&stop()}},init(){const p=$("#tool");if(p)label(p.dataset.id)},refresh(){this.init()},characters:CH.length,monsters:MON.length,scenes:Object.keys(SC).length};
JT.Magic=Magic;JT.UsageManager=Usage;JT.CharacterManager={count:CH.length,render:i=>mascot(CH[i],i)};JT.MonsterManager={count:MON.length,show:Lock.show};JT.MagicAnimationManager={scenes:Object.keys(SC),start};
Magic.init();
})();
