window.JT_TOOLS=window.JT_TOOLS||{};
(function(){
const h=(t,a={},...c)=>{const e=document.createElement(t);for(const k in a){if(k==="class")e.className=a[k];else if(k.slice(0,2)==="on")e.addEventListener(k.slice(2),a[k]);else e.setAttribute(k,a[k])}e.append(...c);return e};
const B=(t,c="btn",f)=>h("button",{class:c,type:"button",onclick:f},t);
const PERM=t=>h("p",{},`This tool needs ${t} access. Your browser will ask for permission only after you press Start. Nothing is recorded or uploaded; everything stays on your device.`);
const errBox=()=>{const e=h("p",{class:"err",role:"alert"});e.hidden=true;e.show=m=>{e.textContent=typeof m==="string"?m:"Something went wrong. Please try again.";e.hidden=false};return e};
const vid=()=>{const v=h("video",{class:"vid",playsinline:"",autoplay:"",muted:""});v.muted=true;return v};
const dl=(box,blob,name)=>{const old=box.querySelector("a");if(old){URL.revokeObjectURL(old.href)}box.textContent="";const u=URL.createObjectURL(blob);box.append(h("img",{src:u,alt:"Captured image",style:"max-width:100%;border-radius:12px;margin-top:10px"}),h("div",{class:"row"},h("a",{class:"btn pri",href:u,download:name},"Download image")))};
const shot=(video,box)=>{if(!video.videoWidth)return JT.toast("The video is not ready yet.","err");const c=document.createElement("canvas");c.width=video.videoWidth;c.height=video.videoHeight;c.getContext("2d").drawImage(video,0,0);c.toBlob(b=>{if(!b)return JT.toast("Could not save the image.","err");dl(box,b,"jadon-tools-capture.png");c.width=c.height=1},"image/png")};
const cam=(capture)=>({mount(r){let s=null;const v=vid(),info=h("p"),msg=errBox(),box=h("div"),fc=h("select",{"aria-label":"Camera"},h("option",{value:"user"},"Front camera"),h("option",{value:"environment"},"Back camera")),st=B("Start camera","btn pri"),sp=B("Stop"),cp=B("Take photo","btn pri");sp.disabled=cp.disabled=true;
const end=()=>{JT.media.stop(s);s=null;v.srcObject=null;st.disabled=false;sp.disabled=cp.disabled=true};
st.onclick=async()=>{msg.hidden=true;try{s=await JT.media.start({opts:{video:capture?{facingMode:{ideal:fc.value}}:true,audio:false}});v.srcObject=s;await v.play().catch(()=>{});const t=s.getVideoTracks()[0],g=t.getSettings();info.textContent=`${t.label||"Camera"} · ${g.width||"?"}×${g.height||"?"}`;st.disabled=true;sp.disabled=false;cp.disabled=false;t.onended=end}catch(e){msg.show(e)}};
sp.onclick=end;cp.onclick=()=>shot(v,box);r.append(PERM("camera"),capture?h("label",{},"Camera"):h("span"),capture?fc:h("span"),h("div",{class:"row"},st,capture?cp:h("span"),sp),msg,v,info,box);return end}});
const mic={mount(r){let s=null,ac=null,raf=0;const msg=errBox(),bar=h("div",{style:"height:18px;border-radius:9px;background:var(--bg2);border:1px solid var(--bd);overflow:hidden"},h("div",{style:"height:100%;width:0;background:linear-gradient(90deg,#22c55e,#06d6ff);transition:width .08s"})),lab=h("p",{"aria-live":"off"},"Level: –"),st=B("Start microphone","btn pri"),sp=B("Stop");sp.disabled=true;
const end=()=>{cancelAnimationFrame(raf);ac&&ac.close().catch(()=>{});ac=null;JT.media.stop(s);s=null;st.disabled=false;sp.disabled=true;bar.firstChild.style.width="0"};
st.onclick=async()=>{msg.hidden=true;try{s=await JT.media.start({opts:{audio:true,video:false}});const A=window.AudioContext||window.webkitAudioContext;if(!A)throw"Audio is not supported by your browser.";ac=new A();const src=ac.createMediaStreamSource(s),an=ac.createAnalyser();an.fftSize=512;src.connect(an);const d=new Uint8Array(an.fftSize);st.disabled=true;sp.disabled=false;const t=s.getAudioTracks()[0];lab.textContent="Listening on: "+(t.label||"microphone");const tick=()=>{an.getByteTimeDomainData(d);let m=0;for(const x of d)m+=((x-128)/128)**2;const rms=Math.sqrt(m/d.length),p=Math.min(100,Math.round(rms*300));bar.firstChild.style.width=p+"%";lab.textContent=`Input level: ${p}%${p<2?" (no sound detected)":""}`;raf=requestAnimationFrame(tick)};tick()}catch(e){end();msg.show(e)}};
sp.onclick=end;r.append(PERM("microphone"),h("div",{class:"row"},st,sp),msg,bar,lab);return end}};
Object.assign(window.JT_TOOLS,{
"camera-test":cam(false),"webcam-photo-capture":cam(true),"microphone-test":mic,
"screen-capture":{mount(r){let s=null;const v=vid(),msg=errBox(),box=h("div"),st=B("Start screen capture","btn pri"),sp=B("Stop"),cp=B("Save screenshot of current frame");sp.disabled=cp.disabled=true;const end=()=>{JT.media.stop(s);s=null;v.srcObject=null;st.disabled=false;sp.disabled=cp.disabled=true};
st.onclick=async()=>{msg.hidden=true;try{s=await JT.media.start({screen:1,opts:{video:true,audio:false}});v.srcObject=s;await v.play().catch(()=>{});st.disabled=true;sp.disabled=cp.disabled=false;s.getVideoTracks()[0].onended=end}catch(e){msg.show(e)}};sp.onclick=end;cp.onclick=()=>shot(v,box);
r.append(PERM("screen-sharing"),h("p",{},"Screen capture is not available in most mobile browsers. Your browser lets you choose what to share, and only that is previewed here."),h("div",{class:"row"},st,cp,sp),msg,v,box);return end}},
"qr-scanner":{mount(r){const D=window.BarcodeDetector,ABS=u=>new URL((document.documentElement.dataset.root||"./")+u,location.href).href;let s=null,iv=0,det=null,last="",busy=false;const v=vid(),msg=errBox(),res=h("output",{class:"pad",style:"text-align:left;word-break:break-all"},"Scan result will appear here"),st=B("Start camera scanner","btn pri"),sp=B("Stop"),cp=B("Copy result"),op=B("Open link"),fi=h("input",{type:"file",accept:"image/png,image/jpeg,image/webp",id:"qrfile","aria-label":"Image containing a QR code"});sp.disabled=true;cp.hidden=op.hidden=true;
const show=t=>{last=t;res.textContent=t;cp.hidden=false;op.hidden=!/^https?:\/\//i.test(t)};
const lib=()=>JT.lib(ABS("js/qrdecode.js"));
const bd=async el=>{if(!D)return null;try{det=det||new D({formats:["qr_code"]});const f=await det.detect(el);return f.length&&f[0].rawValue?f[0].rawValue:null}catch(e){return null}};
const grab=(el,w,h)=>{const m=Math.min(1,900/Math.max(w,h)),c=document.createElement("canvas");c.width=Math.round(w*m);c.height=Math.round(h*m);const x=c.getContext("2d",{willReadFrequently:true});x.drawImage(el,0,0,c.width,c.height);return x.getImageData(0,0,c.width,c.height)};
const any=async(el,w,h)=>{const t=await bd(el);if(t)return t;await lib();return window.JTQR.decode(grab(el,w,h))};
const end=()=>{clearInterval(iv);iv=0;JT.media.stop(s);s=null;v.srcObject=null;st.disabled=false;sp.disabled=true};
st.onclick=async()=>{msg.hidden=true;cp.hidden=op.hidden=true;try{await lib();s=await JT.media.start({opts:{video:{facingMode:{ideal:"environment"}},audio:false}});v.srcObject=s;await v.play().catch(()=>{});st.disabled=true;sp.disabled=false;iv=setInterval(async()=>{if(busy||!v.videoWidth)return;busy=true;try{const t=await any(v,v.videoWidth,v.videoHeight);if(t){show(t);end()}}catch(e){}busy=false},300)}catch(e){end();msg.show(e)}};
fi.onchange=async()=>{msg.hidden=true;cp.hidden=op.hidden=true;const f=fi.files[0];if(!f)return;try{if(!/^image\/(png|jpeg|webp)$/.test(f.type)||f.size>25e6)throw"Choose a PNG, JPG or WebP image under 25 MB.";let bm;try{bm=await createImageBitmap(f)}catch(e){throw"This image could not be read."}const t=await any(bm,bm.width,bm.height);bm.close&&bm.close();if(!t)throw"No QR code was found in that image. Try a sharper, larger picture.";show(t)}catch(e){msg.show(e)}};
sp.onclick=end;cp.onclick=()=>JT.copy(last);op.onclick=()=>{if(/^https?:\/\//i.test(last)&&confirm("Open this link in a new tab?\n\n"+last))window.open(last,"_blank","noopener,noreferrer")};
r.append(PERM("camera"),h("div",{class:"row"},st,sp),h("label",{for:"qrfile"},"Or choose an image that contains a QR code"),fi,msg,v,res,h("div",{class:"row"},cp,op));return end}},
"touchscreen-tester":{mount(r){const c=h("canvas",{style:"width:100%;height:280px;touch-action:none;border:1px dashed var(--bd);border-radius:16px;background:var(--bg2)"}),o=h("p",{"aria-live":"off"},`Max touch points reported: ${navigator.maxTouchPoints||0}. Touch the box below with one or more fingers.`),P=new Map();let raf=0;const fit=()=>{const b=c.getBoundingClientRect();c.width=b.width;c.height=b.height};const paint=()=>{const x=c.getContext("2d");x.clearRect(0,0,c.width,c.height);x.fillStyle="#06d6ff";x.font="14px system-ui";P.forEach((p,id)=>{x.beginPath();x.arc(p.x,p.y,26,0,7);x.globalAlpha=.35;x.fill();x.globalAlpha=1;x.fillText(`${p.type} ${id}`,p.x+30,p.y)});o.textContent=`Active pointers: ${P.size}. Max touch points reported: ${navigator.maxTouchPoints||0}.`};
const mv=e=>{const b=c.getBoundingClientRect();P.set(e.pointerId,{x:e.clientX-b.left,y:e.clientY-b.top,type:e.pointerType});paint()},up=e=>{P.delete(e.pointerId);paint()};c.addEventListener("pointerdown",mv);c.addEventListener("pointermove",e=>{if(P.has(e.pointerId))mv(e)});["pointerup","pointercancel","pointerleave"].forEach(n=>c.addEventListener(n,up));r.append(o,c);setTimeout(fit,0);addEventListener("resize",fit);return()=>removeEventListener("resize",fit)}},
"alarm-timer":{mount(r){let iv=0,ac=null,osc=null,target=null;const t=h("input",{type:"time",id:"al"}),l=h("input",{type:"text",maxlength:60,placeholder:"Label (optional)","aria-label":"Alarm label"}),o=h("output",{class:"big"},"No alarm set"),go=B("Set alarm","btn pri"),cn=B("Cancel"),ds=B("Dismiss");ds.hidden=true;
const quiet=()=>{try{osc&&osc.stop();ac&&ac.close()}catch(e){}osc=ac=null;ds.hidden=true},stop=()=>{clearInterval(iv);iv=0;target=null;o.textContent="No alarm set"};
const ring=()=>{stop();o.textContent="⏰ "+(l.value||"Alarm")+" is ringing";ds.hidden=false;JT.toast("Alarm!");try{const A=window.AudioContext||window.webkitAudioContext;ac=new A();osc=ac.createOscillator();osc.frequency.value=880;osc.connect(ac.destination);osc.start()}catch(e){}};
go.onclick=()=>{if(!t.value)return JT.toast("Choose a time first.","err");quiet();const[H,M]=t.value.split(":"),n=new Date(),x=new Date(n.getFullYear(),n.getMonth(),n.getDate(),+H,+M,0);if(x<=n)x.setDate(x.getDate()+1);target=x;clearInterval(iv);iv=setInterval(()=>{const d=target-Date.now();if(d<=0)return ring();const s=d/1e3|0;o.textContent=`Rings in ${s/3600|0}h ${s/60%60|0}m ${s%60}s`},500)};
cn.onclick=()=>{stop();quiet()};ds.onclick=()=>{quiet();o.textContent="No alarm set"};r.append(h("label",{for:"al"},"Alarm time"),t,l,h("div",{class:"row"},go,cn,ds),o,h("p",{},"The alarm only works while this page stays open in your browser."));return()=>{stop();quiet()}}},
"calendar":{mount(r){let d=new Date();d.setDate(1);let mon=0;const cap=h("h2",{style:"margin:0"}),tb=h("table",{style:"width:100%;border-collapse:collapse;text-align:center;table-layout:fixed"}),sel=h("select",{"aria-label":"First day of week"},h("option",{value:0},"Week starts Sunday"),h("option",{value:1},"Week starts Monday")),draw=()=>{cap.textContent=d.toLocaleDateString(undefined,{month:"long",year:"numeric"});tb.textContent="";const s=+sel.value,names=[...Array(7)].map((_,i)=>new Date(2023,0,1+(i+s)%7).toLocaleDateString(undefined,{weekday:"short"}));tb.append(h("thead",{},h("tr",{},...names.map(n=>h("th",{scope:"col",style:"padding:8px;color:var(--mut)"},n)))));const b=h("tbody"),first=(d.getDay()-s+7)%7,days=new Date(d.getFullYear(),d.getMonth()+1,0).getDate(),now=new Date();let day=1;for(let w=0;w<6&&day<=days;w++){const tr=h("tr");for(let k=0;k<7;k++){const td=h("td",{style:"padding:10px 4px;border:1px solid var(--bd)"});if((w||k>=first)&&day<=days){td.textContent=day;if(day===now.getDate()&&d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()){td.setAttribute("aria-current","date");td.style.cssText+=";background:var(--grad);color:#fff;font-weight:700"}day++}tr.append(td)}b.append(tr)}tb.append(b)};
const mv=n=>()=>{d=new Date(d.getFullYear(),d.getMonth()+n,1);draw()};sel.onchange=draw;r.append(h("div",{class:"row",style:"align-items:center;justify-content:space-between"},B("← Previous","btn",mv(-1)),cap,B("Next →","btn",mv(1))),h("div",{class:"row"},B("Today","btn",()=>{d=new Date();d.setDate(1);draw()}),sel),tb);draw()}},
"world-clock":{mount(r){const Z=["UTC","America/New_York","America/Chicago","America/Los_Angeles","America/Sao_Paulo","Europe/London","Europe/Paris","Europe/Moscow","Africa/Cairo","Asia/Dubai","Asia/Kolkata","Asia/Singapore","Asia/Tokyo","Australia/Sydney","Pacific/Auckland"],local=Intl.DateTimeFormat().resolvedOptions().timeZone;let L=[local,"UTC","America/New_York","Asia/Tokyo"].filter((x,i,a)=>a.indexOf(x)===i);const list=h("div",{class:"grid"}),sel=h("select",{"aria-label":"Time zone"},...Z.map(z=>h("option",{},z))),f=z=>{try{return new Date().toLocaleTimeString([],{timeZone:z,hour:"2-digit",minute:"2-digit",second:"2-digit"})}catch(e){return"–"}},dt=z=>new Date().toLocaleDateString([],{timeZone:z,weekday:"short",day:"numeric",month:"short"}),draw=()=>{list.textContent="";L.forEach(z=>{const t=h("output",{class:"big",style:"font-size:1.6rem"},f(z));t.dataset.z=z;list.append(h("div",{class:"card"},h("strong",{},z.replace(/_/g," ")+(z===local?" (your time zone)":"")),t,h("small",{class:"d"},dt(z)),h("button",{class:"btn",type:"button",style:"margin-top:8px",onclick:()=>{L=L.filter(x=>x!==z);draw()},"aria-label":"Remove "+z},"Remove")))})},iv=setInterval(()=>{list.querySelectorAll("output").forEach(o=>o.textContent=f(o.dataset.z))},1e3);r.append(h("div",{class:"row"},sel,B("Add clock","btn pri",()=>{if(!L.includes(sel.value)&&L.length<12){L.push(sel.value);draw()}})),list);draw();return()=>clearInterval(iv)}}
});})();
