window.JT_TOOLS=window.JT_TOOLS||{};
(function(){
const MB=1048576,fmtB=b=>b<1024?b+" B":b<MB?(b/1024).toFixed(1)+" KB":b<1024*MB?(b/MB).toFixed(2)+" MB":(b/MB/1024).toFixed(2)+" GB";
const num=(x,n)=>{if(x===""||x==null||isNaN(x))throw n+" must be a number.";return +x};
const int=(x,n,a,b)=>{const v=num(x,n);if(!Number.isInteger(v)||v<a||v>b)throw`${n} must be a whole number from ${a} to ${b}.`;return v};
const F=(id,label,accept,hint,multi)=>({id,label,type:"file",accept,hint,multi}),SEL=(id,l,o,d)=>({id,label:l,type:"select",opts:o,def:d||o[0]}),N=(id,l,d)=>({id,label:l,type:"number",def:d}),TA=(id,l)=>({id,label:l,type:"textarea"}),C=(id,l,d)=>({id,label:l,type:"color",def:d});
const h=(t,a={},...c)=>{const e=document.createElement(t);for(const k in a){if(k==="class")e.className=a[k];else if(k.slice(0,2)==="on")e.addEventListener(k.slice(2),a[k]);else e.setAttribute(k,a[k])}e.append(...c);return e};
const IM={mime:["image/jpeg","image/png","image/webp","image/gif","image/bmp"],ext:["jpg","jpeg","png","webp","gif","bmp"],name:"JPG, PNG, WebP, GIF or BMP"},ONLY=(mime,ext,name)=>({mime,ext,name});
const JPG=ONLY(["image/jpeg"],["jpg","jpeg"],"a JPG/JPEG file"),PNG=ONLY(["image/png"],["png"],"a PNG file"),WEBP=ONLY(["image/webp"],["webp"],"a WebP file"),PDFT=ONLY(["application/pdf"],["pdf"],"a PDF file");
const acc=r=>r.mime.join(",")+","+r.ext.map(x=>"."+x).join(",");
const chk=(f,r,max=25*MB)=>{const e=(f.name.split(".").pop()||"").toLowerCase();if(!r.ext.includes(e))throw`"${f.name}" is not supported. Please choose ${r.name}.`;if(f.type&&!r.mime.includes(f.type))throw`"${f.name}" does not look like a valid file of that type.`;if(f.size===0)throw`"${f.name}" is empty.`;if(f.size>max)throw`"${f.name}" is too large (${fmtB(f.size)}). The limit is ${fmtB(max)}.`;return f};
const one=(a,r,max)=>{if(!a||!a.length)throw"Choose a file first.";if(a.length>1)throw"Please choose one file only.";return chk(a[0],r,max)};
const mimeOf=f=>f.type||({jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",webp:"image/webp",gif:"image/gif",bmp:"image/bmp"})[f.name.split(".").pop().toLowerCase()];
const iw=i=>i.naturalWidth||i.width,ih=i=>i.naturalHeight||i.height;
const loadImg=async f=>{let i;if(window.createImageBitmap){try{i=await createImageBitmap(f)}catch(e){}}if(!i){const u=URL.createObjectURL(f);try{i=await new Promise((s,j)=>{const m=new Image();m.onload=()=>s(m);m.onerror=()=>j("This image could not be read. Please try another file.");m.src=u})}finally{URL.revokeObjectURL(u)}}if(iw(i)*ih(i)>36e6){i.close&&i.close();throw"This image is too large to process in the browser (over 36 megapixels)."}return i};
const cv=(w,h)=>{const c=document.createElement("canvas");c.width=Math.max(1,Math.round(w));c.height=Math.max(1,Math.round(h));return c};
const draw=(i,w,h)=>{const c=cv(w||iw(i),h||ih(i)),x=c.getContext("2d");x.imageSmoothingQuality="high";x.drawImage(i,0,0,c.width,c.height);return c};
const toBlob=(c,t,q)=>new Promise((s,j)=>c.toBlob(b=>{if(!b)j("This browser could not create that image.");else if(b.type!==t)j(`This browser cannot save ${t.replace("image/","").toUpperCase()} images. Try another output format.`);else s(b)},t,q));
const EXT={"image/jpeg":"jpg","image/png":"png","image/webp":"webp"};
const flat=c=>{const d=cv(c.width,c.height),x=d.getContext("2d");x.fillStyle="#fff";x.fillRect(0,0,d.width,d.height);x.drawImage(c,0,0);return d};
const save=(c,t,q)=>toBlob(t==="image/jpeg"?flat(c):c,t,q);
const TYPE={PNG:"image/png",JPEG:"image/jpeg",WebP:"image/webp"};
const outType=(o,f)=>{if(TYPE[o])return TYPE[o];const m=mimeOf(f);return m==="image/jpeg"||m==="image/webp"?m:"image/png"};
const R=(b,name,text)=>({text,files:[{blob:b,name:`jadon-tools-${name}.${EXT[b.type]||"png"}`,type:b.type}]});
const info=(f,i,c,b)=>`Original: ${iw(i)}×${ih(i)}px, ${fmtB(f.size)}\nResult: ${c.width}×${c.height}px, ${fmtB(b.size)}\n${b.size<=f.size?"Smaller by "+Math.round((1-b.size/f.size)*100)+"%":"Larger by "+Math.round((b.size/f.size-1)*100)+"%"}`;
const imgTool=(name,fields,proc,o={})=>{const r=o.only||IM;return{fields:[F("f","Image",acc(r),`${r.name}, up to 25 MB.`),...fields,...(o.fixed?[]:[SEL("o","Output format",o.fmts||["Same as input","PNG","JPEG","WebP"])]),...(o.q?[N("q","Quality (10-100)",o.q)]:[])],
run:async v=>{const f=one(v.f,r);const q=o.q?int(v.q,"Quality",10,100)/100:.92,i=await loadImg(f);try{const c=await proc(i,v,f),t=o.fixed||outType(v.o,f),b=await save(c,t,q);let x=info(f,i,c,b);if(t==="image/png"&&o.q)x+="\nPNG is lossless, so quality does not apply. Choose WebP or JPEG for smaller files.";return R(b,name,x)}finally{i.close&&i.close()}}}};
const px=(i,fn)=>{const c=draw(i),x=c.getContext("2d"),d=x.getImageData(0,0,c.width,c.height);fn(d.data);x.putImageData(d,0,0);return c};
const rot=(i,deg)=>{const W=iw(i),H=ih(i),s=deg%180!==0,c=cv(s?H:W,s?W:H),x=c.getContext("2d");x.translate(c.width/2,c.height/2);x.rotate(deg*Math.PI/180);x.drawImage(i,-W/2,-H/2);return c};
const cnv=(name,only,fixed)=>imgTool(name,[],i=>draw(i),{only,fixed,q:92});
const POS=["Top left","Top center","Top right","Center","Bottom left","Bottom center","Bottom right"];
const gcd=(a,b)=>b?gcd(b,a%b):a;
// ---------- PDF writer (no library) ----------
const enc=new TextEncoder();
const mkPdf=objs=>{const parts=[],offs=[];let len=0;const push=b=>{if(typeof b==="string")b=enc.encode(b);parts.push(b);len+=b.length};push("%PDF-1.4\n");objs.forEach((o,i)=>{offs.push(len);push(`${i+1} 0 obj\n`);(Array.isArray(o)?o:[o]).forEach(push);push("\nendobj\n")});const x=len;push(`xref\n0 ${objs.length+1}\n0000000000 65535 f \n`+offs.map(o=>String(o).padStart(10,"0")+" 00000 n \n").join("")+`trailer\n<< /Size ${objs.length+1} /Root 1 0 R >>\nstartxref\n${x}\n%%EOF`);return new Blob(parts,{type:"application/pdf"})};
const SIZES={A4:[595,842],Letter:[612,792]};
const imgPdf=async(files,size)=>{const objs=[null,null],kids=[];let n=0;for(const f of files){const i=await loadImg(f);try{const c=flat(draw(i)),b=await toBlob(c,"image/jpeg",.92),by=new Uint8Array(await b.arrayBuffer()),w=c.width,h=c.height;let pw,ph,dw,dh;if(size==="Fit to image"){pw=w*.75;ph=h*.75;dw=pw;dh=ph}else{[pw,ph]=SIZES[size];const s=Math.min((pw-48)/w,(ph-48)/h);dw=w*s;dh=h*s}const x=(pw-dw)/2,y=(ph-dh)/2,id=3+3*n,ct=`q ${dw.toFixed(2)} 0 0 ${dh.toFixed(2)} ${x.toFixed(2)} ${y.toFixed(2)} cm /Im0 Do Q`;kids.push(id+" 0 R");objs.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pw.toFixed(2)} ${ph.toFixed(2)}] /Resources << /XObject << /Im0 ${id+2} 0 R >> >> /Contents ${id+1} 0 R >>`,`<< /Length ${ct.length} >>\nstream\n${ct}\nendstream`,[`<< /Type /XObject /Subtype /Image /Width ${w} /Height ${h} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${by.length} >>\nstream\n`,by,"\nendstream"]);n++;c.width=c.height=1}finally{i.close&&i.close()}}objs[0]="<< /Type /Catalog /Pages 2 0 R >>";objs[1]=`<< /Type /Pages /Kids [${kids.join(" ")}] /Count ${n} >>`;return mkPdf(objs)};
const pdfImg=(only,multi,name)=>({fields:[F("f",multi?"Images":"Image",acc(only),`${only.name}, up to 25 MB each${multi?" (up to 30 images, kept in the order chosen)":""}.`,multi),SEL("s","Page size",["Fit to image","A4","Letter"],"A4")],run:async v=>{const a=v.f;if(!a.length)throw"Choose a file first.";if(!multi&&a.length>1)throw"Please choose one file only.";if(a.length>30)throw"Please choose 30 images or fewer.";a.forEach(f=>chk(f,only));const b=await imgPdf(a,v.s);return{text:`Created a PDF with ${a.length} page(s), ${fmtB(b.size)}.`,files:[{blob:b,name:`jadon-tools-${name}.pdf`,type:"application/pdf"}]}}});
const WIN={8217:146,8216:145,8220:147,8221:148,8211:150,8212:151,8226:149,8230:133};
const textPdf=(text,size,fs)=>{let bad=0;const [pw,ph]=SIZES[size],m=48,cpl=Math.max(20,Math.floor((pw-2*m)/(fs*.56))),lh=fs*1.4,per=Math.floor((ph-2*m)/lh),L=[];text.replace(/\r/g,"").split("\n").forEach(l=>{l=l.replace(/\t/g,"    ");if(!l){L.push("");return}while(l.length>cpl){let k=l.lastIndexOf(" ",cpl);if(k<1)k=cpl;L.push(l.slice(0,k));l=l.slice(k).replace(/^ /,"")}L.push(l)});
const en=s=>{const o=[];for(const ch of s){let c=ch.codePointAt(0);if(WIN[c])c=WIN[c];else if(!((c>=32&&c<127)||(c>=160&&c<256))){c=63;bad++}if(c===40||c===41||c===92)o.push(92);o.push(c)}return new Uint8Array(o)};
const pages=[];for(let i=0;i<L.length||i===0;i+=per)pages.push(L.slice(i,i+per));const objs=[null,null,"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>"],kids=[];
pages.forEach((p,n)=>{const id=4+2*n,ch=[enc.encode(`BT /F1 ${fs} Tf ${lh.toFixed(1)} TL ${m} ${ph-m-fs} Td\n`)];p.forEach(l=>{ch.push(enc.encode("("),en(l),enc.encode(") Tj T*\n"))});ch.push(enc.encode("ET"));const len=ch.reduce((s,x)=>s+x.length,0);kids.push(id+" 0 R");objs.push(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${pw} ${ph}] /Resources << /Font << /F1 3 0 R >> >> /Contents ${id+1} 0 R >>`,[`<< /Length ${len} >>\nstream\n`,...ch,"\nendstream"])});
objs[0]="<< /Type /Catalog /Pages 2 0 R >>";objs[1]=`<< /Type /Pages /Kids [${kids.join(" ")}] /Count ${pages.length} >>`;return{blob:mkPdf(objs),pages:pages.length,bad}};
// ---------- PDF libraries (loaded only when needed) ----------
const ROOT=()=>document.documentElement.dataset.root||"./";
const ABS=p=>new URL(ROOT()+p,location.href).href;
const PL=async()=>{await JT.lib(ABS("js/vendor/pdf-lib.min.js"));return window.PDFLib};
const PJ=async()=>{const L=await import(ABS("js/vendor/pdf.min.mjs"));L.GlobalWorkerOptions.workerSrc=ABS("js/vendor/pdf.worker.min.mjs");return L};
const readPdf=async(f,max=50*MB)=>{chk(f,PDFT,max);const b=new Uint8Array(await f.arrayBuffer());if(String.fromCharCode(...b.slice(0,5))!=="%PDF-")throw`"${f.name}" is not a valid PDF file.`;return b};
const loadDoc=async f=>{const L=await PL(),b=await readPdf(f);try{return await L.PDFDocument.load(b)}catch(e){throw/encrypt/i.test(e&&e.message)?`"${f.name}" is password-protected and cannot be processed.`:`"${f.name}" could not be read. It may be damaged.`}};
const PR=(bytes,name,text)=>({text,files:[{blob:new Blob([bytes],{type:"application/pdf"}),name:`jadon-tools-${name}.pdf`,type:"application/pdf"}]});
const ranges=(s,max)=>{const out=[];if(!s.trim())throw"Enter page numbers, for example 1-3,5.";s.split(",").forEach(p=>{p=p.trim();const m=/^(\d+)(?:\s*-\s*(\d+))?$/.exec(p);if(!m)throw`"${p}" is not a valid page or range.`;const a=+m[1],b=m[2]?+m[2]:a;if(a<1||b<1||a>max||b>max)throw`Page numbers must be between 1 and ${max}.`;const st=a<=b?1:-1;for(let k=a;k!==b+st;k+=st)out.push(k-1);if(out.length>2000)throw"Too many pages requested."});return out};
const PF=(multi)=>F("f",multi?"PDF files":"PDF file",acc(PDFT),`PDF, up to 50 MB${multi?" each":""}.`,multi);
const words=t=>(t.trim().match(/\S+/g)||[]).length;
const MAGIC=[["PNG image",[0x89,0x50,0x4e,0x47],0,["png"]],["JPEG image",[0xff,0xd8,0xff],0,["jpg","jpeg"]],["GIF image",[0x47,0x49,0x46,0x38],0,["gif"]],["PDF document",[0x25,0x50,0x44,0x46],0,["pdf"]],["ZIP-based file (ZIP, DOCX, XLSX, PPTX, APK…)",[0x50,0x4b,3,4],0,["zip","docx","xlsx","pptx","apk","jar","odt","epub"]],["BMP image",[0x42,0x4d],0,["bmp"]],["MP3 audio",[0x49,0x44,0x33],0,["mp3"]],["MP4/MOV video",[0x66,0x74,0x79,0x70],4,["mp4","m4a","mov","m4v"]],["GZIP archive",[0x1f,0x8b],0,["gz","tgz"]]];
Object.assign(window.JT_TOOLS,{
"image-compressor":imgTool("compressed-image",[],i=>draw(i),{q:80}),
"image-resizer":imgTool("resized-image",[N("w","Width (px)"),N("h","Height (px)"),{id:"k",label:"Keep aspect ratio",type:"checkbox",def:true}],(i,v)=>{const W=iw(i),H=ih(i);let w=v.w===""?0:int(v.w,"Width",1,10000),h=v.h===""?0:int(v.h,"Height",1,10000);if(!w&&!h)throw"Enter a width, a height, or both.";if(v.k){if(w&&h){const s=Math.min(w/W,h/H);w=W*s;h=H*s}else if(w)h=H*w/W;else w=W*h/H}else{w=w||W;h=h||H}return draw(i,w,h)},{q:92}),
"image-cropper":imgTool("cropped-image",[N("x","Left (px)",0),N("y","Top (px)",0),N("w","Crop width (px)"),N("h","Crop height (px)")],(i,v)=>{const W=iw(i),H=ih(i),x=int(v.x,"Left",0,99999),y=int(v.y,"Top",0,99999),w=int(v.w,"Crop width",1,99999),h=int(v.h,"Crop height",1,99999);if(x+w>W||y+h>H)throw`The crop area is outside the image (${W}×${H}px).`;const c=cv(w,h);c.getContext("2d").drawImage(i,x,y,w,h,0,0,w,h);return c}),
"image-rotator":imgTool("rotated-image",[SEL("a","Rotate",["90° clockwise","180°","90° counter-clockwise"])],(i,v)=>rot(i,{"90° clockwise":90,"180°":180,"90° counter-clockwise":270}[v.a])),
"image-flipper":imgTool("flipped-image",[SEL("d","Flip",["Horizontal (mirror)","Vertical"])],(i,v)=>{const c=cv(iw(i),ih(i)),x=c.getContext("2d");if(v.d.startsWith("H")){x.translate(c.width,0);x.scale(-1,1)}else{x.translate(0,c.height);x.scale(1,-1)}x.drawImage(i,0,0);return c}),
"image-converter":imgTool("converted-image",[],i=>draw(i),{fmts:["PNG","JPEG","WebP"],q:92}),
"jpg-to-png":cnv("jpg-to-png",JPG,"image/png"),"png-to-jpg":cnv("png-to-jpg",PNG,"image/jpeg"),"jpg-to-webp":cnv("jpg-to-webp",JPG,"image/webp"),"png-to-webp":cnv("png-to-webp",PNG,"image/webp"),"webp-to-jpg":cnv("webp-to-jpg",WEBP,"image/jpeg"),"webp-to-png":cnv("webp-to-png",WEBP,"image/png"),
"image-to-pdf":pdfImg(IM,false,"image-to-pdf"),"jpg-to-pdf":pdfImg(JPG,false,"jpg-to-pdf"),"png-to-pdf":pdfImg(PNG,false,"png-to-pdf"),"images-to-pdf":pdfImg(IM,true,"images-to-pdf"),
"text-to-pdf":{fields:[TA("t","Text"),SEL("s","Page size",["A4","Letter"]),N("z","Font size (8-24)",12)],run:v=>{if(!v.t.trim())throw"Enter some text first.";if(v.t.length>2e5)throw"Text is too long (limit 200,000 characters).";const r=textPdf(v.t,v.s,int(v.z,"Font size",8,24));return{text:`Created a ${r.pages}-page PDF (${fmtB(r.blob.size)}).`+(r.bad?`\n${r.bad} character(s) outside the Latin set were replaced with "?". This tool supports Latin characters only.`:""),files:[{blob:r.blob,name:"jadon-tools-text-to-pdf.pdf",type:"application/pdf"}]}}},
"photo-size-reducer":{fields:[F("f","Photo",acc(IM),"JPG, PNG, WebP, GIF or BMP, up to 25 MB."),N("k","Target size (KB)",200),SEL("o","Output format",["JPEG","WebP"])],run:async v=>{const f=one(v.f,IM),k=int(v.k,"Target size",10,20000)*1024,t=TYPE[v.o],i=await loadImg(f);try{const base=draw(i);let best=null,c=base;for(let s=0;s<6&&!best;s++){if(s)c=draw(i,iw(i)*Math.pow(.8,s),ih(i)*Math.pow(.8,s));if((await save(c,t,.1)).size>k)continue;let lo=.1,hi=.95;best=await save(c,t,.1);for(let n=0;n<7;n++){const q=(lo+hi)/2,b=await save(c,t,q);if(b.size<=k){best=b;lo=q}else hi=q}}if(!best)throw"This photo could not be reduced to that size. Try a larger target.";return R(best,"reduced-photo",info(f,i,c,best))}finally{i.close&&i.close()}}},
"image-dimension-checker":{fields:[F("f","Image",acc(IM),"JPG, PNG, WebP, GIF or BMP, up to 25 MB.")],run:async v=>{const f=one(v.f,IM),i=await loadImg(f),w=iw(i),h=ih(i);i.close&&i.close();const g=gcd(w,h);return `Width: ${w}px\nHeight: ${h}px\nAspect ratio: ${w/g}:${h/g}\nMegapixels: ${(w*h/1e6).toFixed(2)}\nOrientation: ${w>h?"Landscape":w<h?"Portrait":"Square"}\nType: ${mimeOf(f)}`}},
"image-file-size-checker":{fields:[F("f","Image",acc(IM),"JPG, PNG, WebP, GIF or BMP, up to 25 MB.")],run:v=>{const f=one(v.f,IM);return `File: ${f.name}\nSize: ${fmtB(f.size)} (${f.size.toLocaleString()} bytes)\nType: ${mimeOf(f)}`}},
"add-text-to-image":imgTool("image-with-text",[{id:"t",label:"Text",type:"text"},N("z","Font size (% of image width)",6),C("c","Text colour","#ffffff"),SEL("p","Position",POS,"Bottom center")],(i,v)=>{if(!v.t.trim())throw"Enter the text to add.";if(v.t.length>200)throw"Text is too long (200 characters max).";const z=num(v.z,"Font size");if(z<1||z>50)throw"Font size must be 1 to 50.";const c=draw(i),x=c.getContext("2d"),s=c.width*z/100,m=s*.6;x.font=`bold ${s}px system-ui,sans-serif`;x.fillStyle=v.c;x.shadowColor="rgba(0,0,0,.6)";x.shadowBlur=s/6;x.textBaseline="middle";const P=v.p,X=P.includes("left")?m:P.includes("right")?c.width-m:c.width/2,Y=P.startsWith("Top")?m+s/2:P.startsWith("Bottom")?c.height-m-s/2:c.height/2;x.textAlign=P.includes("left")?"left":P.includes("right")?"right":"center";x.fillText(v.t,X,Y,c.width-2*m);return c}),
"add-watermark":imgTool("watermarked-image",[{id:"t",label:"Watermark text",type:"text"},N("z","Text size (% of image width)",5),N("a","Opacity (5-100)",35),SEL("m","Style",["Tiled diagonal","Bottom right corner"])],(i,v)=>{if(!v.t.trim())throw"Enter the watermark text.";if(v.t.length>100)throw"Watermark text is too long.";const z=num(v.z,"Size"),a=int(v.a,"Opacity",5,100);if(z<1||z>30)throw"Size must be 1 to 30.";const c=draw(i),x=c.getContext("2d"),s=c.width*z/100;x.font=`bold ${s}px system-ui,sans-serif`;x.fillStyle=`rgba(255,255,255,${a/100})`;x.strokeStyle=`rgba(0,0,0,${a/200})`;x.lineWidth=Math.max(1,s/18);x.textBaseline="middle";if(v.m==="Tiled diagonal"){const w=x.measureText(v.t).width+s*2,st=s*3.2,d=Math.hypot(c.width,c.height);x.save();x.translate(c.width/2,c.height/2);x.rotate(-Math.PI/6);x.textAlign="center";for(let y=-d/2;y<d/2;y+=st)for(let X=-d/2;X<d/2;X+=w){x.strokeText(v.t,X,y);x.fillText(v.t,X,y)}x.restore()}else{x.textAlign="right";const X=c.width-s/2,Y=c.height-s;x.strokeText(v.t,X,Y);x.fillText(v.t,X,Y)}return c}),
"blur-image":imgTool("blurred-image",[N("r","Blur amount (1-50)",8)],(i,v)=>{const r=int(v.r,"Blur amount",1,50),c=cv(iw(i),ih(i)),x=c.getContext("2d");if("filter"in x){x.filter=`blur(${r}px)`;x.drawImage(i,0,0)}else{const k=1/(1+r),t=draw(i,Math.max(1,iw(i)*k),Math.max(1,ih(i)*k));x.imageSmoothingQuality="high";x.drawImage(t,0,0,c.width,c.height)}return c}),
"pixelate-image":imgTool("pixelated-image",[N("b","Block size (2-100 px)",12)],(i,v)=>{const b=int(v.b,"Block size",2,100),W=iw(i),H=ih(i),t=draw(i,Math.max(1,W/b),Math.max(1,H/b)),c=cv(W,H),x=c.getContext("2d");x.imageSmoothingEnabled=false;x.drawImage(t,0,0,W,H);return c}),
"grayscale-image":imgTool("grayscale-image",[],i=>px(i,p=>{for(let k=0;k<p.length;k+=4){const g=.299*p[k]+.587*p[k+1]+.114*p[k+2];p[k]=p[k+1]=p[k+2]=g}})),
"brightness-adjuster":imgTool("brightness-image",[N("b","Brightness change (-100 to 100)",20)],(i,v)=>{const d=int(v.b,"Brightness",-100,100)*2.55;return px(i,p=>{for(let k=0;k<p.length;k+=4){p[k]+=d;p[k+1]+=d;p[k+2]+=d}})}),
"contrast-adjuster":imgTool("contrast-image",[N("b","Contrast change (-100 to 100)",20)],(i,v)=>{const C=int(v.b,"Contrast",-100,100)*2.55,f=259*(C+255)/(255*(259-C));return px(i,p=>{for(let k=0;k<p.length;k+=4){p[k]=f*(p[k]-128)+128;p[k+1]=f*(p[k+1]-128)+128;p[k+2]=f*(p[k+2]-128)+128}})}),
"screenshot-cropper":imgTool("screenshot-crop",[N("t","Trim from top (px)",0),N("b","Trim from bottom (px)",0),N("l","Trim from left (px)",0),N("r","Trim from right (px)",0)],(i,v)=>{const t=int(v.t,"Top",0,99999),b=int(v.b,"Bottom",0,99999),l=int(v.l,"Left",0,99999),r=int(v.r,"Right",0,99999),w=iw(i)-l-r,H=ih(i)-t-b;if(w<1||H<1)throw"The trim amounts remove the whole image.";const c=cv(w,H);c.getContext("2d").drawImage(i,l,t,w,H,0,0,w,H);return c}),
"image-color-picker":{mount(r){let bm=null;const inp=h("input",{type:"file",accept:acc(IM),"aria-label":"Image"}),cvs=h("canvas",{style:"max-width:100%;border-radius:12px;margin-top:10px;cursor:crosshair;display:none"}),out=h("output",{class:"big"},"Pick an image, then click a pixel"),sw=h("div",{style:"height:48px;border-radius:12px;border:1px solid var(--bd)"}),msg=h("p",{class:"err",role:"alert"});msg.hidden=true;const cp=h("button",{class:"btn",type:"button"},"Copy HEX");let hexv="";
inp.onchange=async()=>{msg.hidden=true;try{const f=chk(inp.files[0],IM);bm&&bm.close&&bm.close();bm=await loadImg(f);const s=Math.min(1,2000/Math.max(iw(bm),ih(bm)));cvs.width=Math.round(iw(bm)*s);cvs.height=Math.round(ih(bm)*s);cvs.getContext("2d",{willReadFrequently:true}).drawImage(bm,0,0,cvs.width,cvs.height);cvs.style.display="block"}catch(e){msg.textContent=typeof e==="string"?e:"This image could not be read.";msg.hidden=false}};
cvs.onclick=e=>{const b=cvs.getBoundingClientRect(),x=Math.min(cvs.width-1,Math.floor((e.clientX-b.left)*cvs.width/b.width)),y=Math.min(cvs.height-1,Math.floor((e.clientY-b.top)*cvs.height/b.height)),d=cvs.getContext("2d").getImageData(x,y,1,1).data;hexv="#"+[...d.slice(0,3)].map(n=>n.toString(16).padStart(2,"0")).join("");out.textContent=`${hexv}  rgb(${d[0]}, ${d[1]}, ${d[2]})`;sw.style.background=hexv};
cp.onclick=()=>hexv?JT.copy(hexv):JT.toast("Click a pixel first","err");r.append(h("label",{},"Image (JPG, PNG, WebP, GIF or BMP)"),inp,msg,cvs,sw,out,h("div",{class:"row"},cp));return()=>{bm&&bm.close&&bm.close()}}},
"pdf-page-counter":{fields:[PF()],run:async v=>{const d=await loadDoc(one(v.f,PDFT,50*MB));return `Pages: ${d.getPageCount()}`}},
"pdf-size-checker":{fields:[PF()],run:async v=>{const f=one(v.f,PDFT,50*MB);await readPdf(f);return `File: ${f.name}\nSize: ${fmtB(f.size)} (${f.size.toLocaleString()} bytes)`}},
"pdf-metadata-viewer":{fields:[PF()],run:async v=>{const f=one(v.f,PDFT,50*MB),b=await readPdf(f),d=await loadDoc(f),g=x=>x==null||x===""?"(not set)":x instanceof Date?x.toISOString():x;return `PDF version: ${String.fromCharCode(...b.slice(5,8))}\nPages: ${d.getPageCount()}\nTitle: ${g(d.getTitle())}\nAuthor: ${g(d.getAuthor())}\nSubject: ${g(d.getSubject())}\nKeywords: ${g(d.getKeywords())}\nCreator: ${g(d.getCreator())}\nProducer: ${g(d.getProducer())}\nCreated: ${g(d.getCreationDate())}\nModified: ${g(d.getModificationDate())}`}},
"pdf-text-extractor":{fields:[PF()],run:async v=>{const f=one(v.f,PDFT,50*MB),b=await readPdf(f),L=await PJ();let d;try{d=await L.getDocument({data:b}).promise}catch(e){throw e&&e.name==="PasswordException"?"This PDF is password-protected and cannot be processed.":"This PDF could not be read. It may be damaged."}try{const n=Math.min(d.numPages,300),o=[];for(let p=1;p<=n;p++){const pg=await d.getPage(p),c=await pg.getTextContent();o.push(`--- Page ${p} ---\n`+c.items.map(x=>x.str).join(" ").replace(/ {2,}/g," ").trim());pg.cleanup()}const t=o.join("\n\n");if(!t.replace(/--- Page \d+ ---|\s/g,""))return"No selectable text was found. This PDF may be scanned images, which needs OCR.";return t+(d.numPages>n?`\n\n(Only the first ${n} pages were read.)`:"")}finally{d.destroy()}}},
"pdf-merger":{fields:[PF(true)],run:async v=>{const a=v.f;if(a.length<2)throw"Choose at least two PDF files.";if(a.length>20)throw"Please choose 20 files or fewer.";const L=await PL(),out=await L.PDFDocument.create(),lst=[];for(const f of a){const s=await loadDoc(f);(await out.copyPages(s,s.getPageIndices())).forEach(p=>out.addPage(p));lst.push(`${f.name}: ${s.getPageCount()} page(s)`)}const by=await out.save();return PR(by,"merged",`Merged ${a.length} files into ${out.getPageCount()} pages (${fmtB(by.length)}).\nOrder: files are merged in the order you selected them.\n`+lst.join("\n"))}},
"pdf-splitter":{fields:[PF(),SEL("m","Mode",["Extract selected pages into one PDF","Split into one PDF per page (up to 30 pages)"]),{id:"r",label:"Pages to extract (e.g. 1-3,5)",type:"text"}],run:async v=>{const d=await loadDoc(one(v.f,PDFT,50*MB)),n=d.getPageCount(),L=await PL();if(v.m.startsWith("Split")){if(n>30)throw`This PDF has ${n} pages. Per-page splitting supports up to 30 pages; use "Extract selected pages" instead.`;const files=[];for(let k=0;k<n;k++){const o=await L.PDFDocument.create();(await o.copyPages(d,[k])).forEach(p=>o.addPage(p));files.push({blob:new Blob([await o.save()],{type:"application/pdf"}),name:`jadon-tools-page-${k+1}.pdf`,type:"application/pdf"})}return{text:`Created ${n} single-page PDFs.`,files}}const idx=ranges(v.r,n),o=await L.PDFDocument.create();(await o.copyPages(d,idx)).forEach(p=>o.addPage(p));return PR(await o.save(),"extracted-pages",`Extracted ${idx.length} page(s) from a ${n}-page PDF.`)}},
"pdf-page-reorder":{fields:[PF(),{id:"r",label:"New page order (e.g. 3,1,2 or 1-3,5)",type:"text"}],run:async v=>{const d=await loadDoc(one(v.f,PDFT,50*MB)),n=d.getPageCount(),idx=ranges(v.r,n),L=await PL(),o=await L.PDFDocument.create();(await o.copyPages(d,idx)).forEach(p=>o.addPage(p));return PR(await o.save(),"reordered",`New PDF has ${idx.length} page(s) from the original ${n}. Pages you leave out are removed and pages you repeat are duplicated.`)}},
"pdf-to-images":{fields:[PF(),SEL("s","Image quality",["Standard (1.5x)","High (2x)","Small (1x)"])],run:async v=>{const f=one(v.f,PDFT,50*MB),b=await readPdf(f),L=await PJ(),sc={"Standard (1.5x)":1.5,"High (2x)":2,"Small (1x)":1}[v.s];let d;try{d=await L.getDocument({data:b}).promise}catch(e){throw e&&e.name==="PasswordException"?"This PDF is password-protected and cannot be processed.":"This PDF could not be read. It may be damaged."}try{const n=Math.min(d.numPages,20),files=[];for(let p=1;p<=n;p++){const pg=await d.getPage(p),vp=pg.getViewport({scale:sc});if(vp.width*vp.height>36e6)throw"A page is too large to render.";const c=cv(vp.width,vp.height);await pg.render({canvasContext:c.getContext("2d"),viewport:vp}).promise;files.push({blob:await toBlob(c,"image/png"),name:`jadon-tools-page-${p}.png`,type:"image/png"});c.width=c.height=1;pg.cleanup()}return{text:`Converted ${n} of ${d.numPages} page(s) to PNG.`+(d.numPages>n?" Only the first 20 pages are converted.":""),files}}finally{d.destroy()}}},
"document-word-counter":{fields:[F("f","Text document",".txt,.csv,.json,.html,.css,.js,.xml,.md,text/plain,text/csv,application/json,text/html,text/css,text/javascript,application/xml,text/xml,text/markdown","TXT, CSV, JSON, HTML, CSS, JS, XML or MD, up to 5 MB. Counts the raw text, including any markup.")],run:async v=>{const r=ONLY(["text/plain","text/csv","application/json","text/html","text/css","text/javascript","application/javascript","application/xml","text/xml","text/markdown","application/x-javascript"],["txt","csv","json","html","css","js","xml","md"],"a text-based document (TXT, CSV, JSON, HTML, CSS, JS, XML or MD)"),f=one(v.f,r,5*MB),t=await f.text(),w=words(t);return `File: ${f.name}\nWords: ${w}\nCharacters: ${[...t].length}\nCharacters (no spaces): ${[...t.replace(/\s/g,"")].length}\nLines: ${t?t.split(/\r?\n/).length:0}\nParagraphs: ${t.split(/\n\s*\n/).filter(x=>x.trim()).length}\nReading time: ${(w/200).toFixed(1)} min`}},
"file-size-checker":{fields:[F("f","Any file","","Any file type. It is only read locally to get its size.",true)],run:v=>{if(!v.f.length)throw"Choose a file first.";return v.f.map(f=>`${f.name}: ${fmtB(f.size)} (${f.size.toLocaleString()} bytes)`).join("\n")}},
"file-extension-checker":{fields:[F("f","Any file","","Any file type. Only the first bytes are read locally.")],run:async v=>{if(!v.f.length)throw"Choose a file first.";if(v.f.length>1)throw"Please choose one file only.";const f=v.f[0],b=new Uint8Array(await f.slice(0,16).arrayBuffer()),e=(f.name.includes(".")?f.name.split(".").pop():"").toLowerCase(),m=MAGIC.find(([n,s,o])=>s.every((x,k)=>b[o+k]===x))||(String.fromCharCode(...b.slice(0,4))==="RIFF"&&String.fromCharCode(...b.slice(8,12))==="WEBP"?["WebP image",0,0,["webp"]]:null);let x=`File: ${f.name}\nExtension: ${e?"."+e:"(none)"}\nType reported by browser: ${f.type||"(unknown)"}\nSize: ${fmtB(f.size)}\n`;if(!m)return x+"Detected by content: not recognised. Detection covers common formats only.";return x+`Detected by content: ${m[0]}\n`+(m[3].includes(e)?"The extension matches the file content.":"Warning: the extension does not match the detected content.")}}
});
})();
