window.JT_TOOLS={
"word-counter":{fields:[{id:"t",label:"Your text",type:"textarea"}],run:v=>{const t=v.t,w=t.trim()?t.trim().split(/\s+/).length:0;return `Words: ${w}\nCharacters: ${[...t].length}\nCharacters (no spaces): ${[...t.replace(/\s/g,"")].length}\nLines: ${t?t.split(/\n/).length:0}\nReading time: ${Math.max(w?1:0,Math.ceil(w/200))} min`}},
"uppercase-converter":{fields:[{id:"t",label:"Your text",type:"textarea"}],run:v=>{if(!v.t)throw"Enter some text first.";return v.t.toUpperCase()}},
"percentage-calculator":{fields:[{id:"a",label:"Percent (%)",type:"number"},{id:"b",label:"Of value",type:"number"},{id:"c",label:"Old value (for change)",type:"number"},{id:"d",label:"New value (for change)",type:"number"}],run:v=>{let o=[];if(v.a!==""&&v.b!=="")o.push(`${v.a}% of ${v.b} = ${+(v.a*v.b/100).toFixed(6)}`);if(v.c!==""&&v.d!==""){if(+v.c===0)throw"Old value cannot be zero.";const p=(v.d-v.c)/Math.abs(v.c)*100;o.push(`Change from ${v.c} to ${v.d} = ${+p.toFixed(4)}% ${p>=0?"increase":"decrease"}`)}if(!o.length)throw"Fill in the first two fields, or the old and new values.";return o.join("\n")}},
"password-generator":{fields:[{id:"n",label:"Length (8-128)",type:"number",def:16},{id:"s",label:"Include symbols",type:"checkbox",def:true}],run:v=>{const n=+v.n;if(!(n>=8&&n<=128))throw"Length must be between 8 and 128.";const cs="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"+(v.s?"!@#$%^&*()-_=+[]{}":"");const lim=Math.floor(4294967296/cs.length)*cs.length;let out="";const b=new Uint32Array(1);while(out.length<n){crypto.getRandomValues(b);if(b[0]<lim)out+=cs[b[0]%cs.length]}return out}},
"json-formatter":{fields:[{id:"t",label:"JSON input",type:"textarea"},{id:"m",label:"Minify instead of beautify",type:"checkbox"}],run:v=>{if(!v.t.trim())throw"Paste some JSON first.";let o;try{o=JSON.parse(v.t)}catch(e){throw"Invalid JSON: "+e.message}return JSON.stringify(o,null,v.m?0:2)}}};
(function(){
const num=(x,n)=>{if(x===""||isNaN(x))throw n+" must be a number.";return +x};
const fmt=x=>String(+Number(x).toPrecision(10));
const conv=(label,U)=>{const k=Object.keys(U),o=k.map(x=>x);return{fields:[{id:"v",label:"Value",type:"number",def:1},{id:"f",label:"From",type:"select",opts:o,def:k[0]},{id:"t",label:"To",type:"select",opts:o,def:k[1]}],run:v=>{const n=num(v.v,"Value");return `${fmt(n)} ${v.f} = ${fmt(n*U[v.f]/U[v.t])} ${v.t}`}}};
const T=(id)=>({fields:[{id:"t",label:"Your text",type:"textarea"}],_:id});
const tx=(fn)=>({fields:[{id:"t",label:"Your text",type:"textarea"}],run:v=>{if(!v.t)throw"Enter some text first.";return fn(v.t)}});
Object.assign(window.JT_TOOLS,{
"lowercase-converter":tx(t=>t.toLowerCase()),
"title-case-converter":tx(t=>t.toLowerCase().replace(/(^|\s)(\p{L})/gu,(m,a,b)=>a+b.toUpperCase())),
"line-counter":tx(t=>`Lines: ${t.split(/\r?\n/).length}\nNon-empty lines: ${t.split(/\r?\n/).filter(l=>l.trim()).length}`),
"character-counter-without-spaces":tx(t=>`Characters without spaces: ${[...t.replace(/\s/g,"")].length}\nCharacters with spaces: ${[...t].length}`),
"slug-generator":tx(t=>{const s=t.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"");if(!s)throw"No letters or numbers found to make a slug.";return s}),
"text-cleaner":tx(t=>t.split(/\r?\n/).map(l=>l.replace(/[ \t]+/g," ").trim()).filter(l=>l).join("\n")),
"sort-text-lines":{fields:[{id:"t",label:"Lines to sort",type:"textarea"},{id:"o",label:"Order",type:"select",opts:["A to Z","Z to A"],def:"A to Z"}],run:v=>{if(!v.t.trim())throw"Enter some lines first.";const l=v.t.split(/\r?\n/).filter(x=>x.trim()).sort((a,b)=>a.localeCompare(b));return(v.o==="Z to A"?l.reverse():l).join("\n")}},
"area-converter":conv("Area",{"mm²":1e-6,"cm²":1e-4,"m²":1,"km²":1e6,"in²":6.4516e-4,"ft²":.09290304,"yd²":.83612736,"acre":4046.8564224,"hectare":1e4,"mi²":2589988.110336}),
"volume-converter":conv("Volume",{"mL":.001,"L":1,"m³":1000,"tsp (US)":.00492892159375,"tbsp (US)":.01478676478125,"fl oz (US)":.0295735295625,"cup (US)":.2365882365,"pint (US)":.473176473,"quart (US)":.946352946,"gallon (US)":3.785411784}),
"speed-converter":conv("Speed",{"m/s":1,"km/h":1/3.6,"mph":.44704,"knot":.5144444444,"ft/s":.3048}),
"energy-converter":conv("Energy",{"J":1,"kJ":1e3,"cal":4.184,"kcal":4184,"Wh":3600,"kWh":3.6e6,"BTU":1055.05585262,"eV":1.602176634e-19}),
"pressure-converter":conv("Pressure",{"Pa":1,"kPa":1e3,"MPa":1e6,"bar":1e5,"atm":101325,"psi":6894.757293168,"mmHg":133.322387415}),
"frequency-converter":conv("Frequency",{"Hz":1,"kHz":1e3,"MHz":1e6,"GHz":1e9,"rpm":1/60}),
"file-size-converter":conv("File size",{"Byte":1,"KB (1024)":1024,"MB (1024²)":1048576,"GB (1024³)":1073741824,"TB (1024⁴)":1099511627776}),
"simple-interest-calculator":{fields:[{id:"p",label:"Principal",type:"number"},{id:"r",label:"Annual rate (%)",type:"number"},{id:"y",label:"Years",type:"number"}],run:v=>{const p=num(v.p,"Principal"),r=num(v.r,"Rate"),y=num(v.y,"Years");if(p<0||r<0||y<0)throw"Values cannot be negative.";const i=p*r*y/100;return `Formula: I = P × R × T / 100\nInterest: ${fmt(i)}\nTotal amount: ${fmt(p+i)}`}},
"compound-interest-calculator":{fields:[{id:"p",label:"Principal",type:"number"},{id:"r",label:"Annual rate (%)",type:"number"},{id:"y",label:"Years",type:"number"},{id:"n",label:"Compounds per year",type:"number",def:12}],run:v=>{const p=num(v.p,"Principal"),r=num(v.r,"Rate"),y=num(v.y,"Years"),n=num(v.n,"Compounds per year");if(p<0||r<0||y<0)throw"Values cannot be negative.";if(n<=0)throw"Compounds per year must be above zero.";const a=p*Math.pow(1+r/100/n,n*y);return `Formula: A = P(1 + r/n)^(n×t)\nFinal amount: ${fmt(a)}\nInterest earned: ${fmt(a-p)}`}},
"emi-calculator":{fields:[{id:"p",label:"Loan amount",type:"number"},{id:"r",label:"Annual rate (%)",type:"number"},{id:"m",label:"Tenure (months)",type:"number"}],run:v=>{const p=num(v.p,"Loan amount"),r=num(v.r,"Rate"),n=num(v.m,"Tenure");if(p<=0||n<=0||r<0)throw"Loan amount and tenure must be above zero, and rate cannot be negative.";const i=r/1200,e=i===0?p/n:p*i*Math.pow(1+i,n)/(Math.pow(1+i,n)-1);return `Monthly EMI: ${e.toFixed(2)}\nTotal payment: ${(e*n).toFixed(2)}\nTotal interest: ${(e*n-p).toFixed(2)}\nInformational only. Actual lender terms may differ.`}},
"average-calculator":{fields:[{id:"t",label:"Numbers (separated by commas, spaces or lines)",type:"textarea"}],run:v=>{const a=v.t.split(/[\s,;]+/).filter(x=>x!=="");if(!a.length)throw"Enter at least one number.";const n=a.map(x=>{if(isNaN(x))throw`"${x}" is not a number.`;return +x}),s=n.reduce((x,y)=>x+y,0),o=[...n].sort((x,y)=>x-y),m=o.length>>1;return `Count: ${n.length}\nSum: ${fmt(s)}\nAverage: ${fmt(s/n.length)}\nMedian: ${fmt(o.length%2?o[m]:(o[m-1]+o[m])/2)}\nMin: ${o[0]}\nMax: ${o[o.length-1]}`}},
"days-between-dates":{fields:[{id:"a",label:"Start date",type:"date"},{id:"b",label:"End date",type:"date"}],run:v=>{if(!v.a||!v.b)throw"Choose both dates.";const d=Math.round((Date.UTC(...v.b.split("-").map((x,i)=>i===1?x-1:+x))-Date.UTC(...v.a.split("-").map((x,i)=>i===1?x-1:+x)))/864e5);return `Days between: ${Math.abs(d)}${d<0?" (end date is before start date)":""}\nWeeks: ${fmt(Math.abs(d)/7)}`}},
"url-encoder":tx(t=>encodeURIComponent(t)),
"url-decoder":tx(t=>{try{return decodeURIComponent(t)}catch(e){throw"This text is not valid percent-encoding."}}),
"timestamp-converter":{fields:[{id:"t",label:"Unix timestamp (seconds or milliseconds) or a date like 2026-01-31T10:00:00Z",type:"text"}],run:v=>{const s=v.t.trim();if(!s)throw"Enter a timestamp or date.";let d;if(/^-?\d+(\.\d+)?$/.test(s)){const n=+s;d=new Date(Math.abs(n)>=1e11?n:n*1e3)}else d=new Date(s);if(isNaN(d))throw"Could not read that value as a date.";return `ISO (UTC): ${d.toISOString()}\nUnix seconds: ${Math.floor(d/1e3)}\nUnix milliseconds: ${d.getTime()}\nYour local time: ${d.toString()}`}}
});})();
(function(){
const num=(x,n)=>{if(x===""||x==null||isNaN(x))throw n+" must be a number.";return +x},fmt=x=>String(+Number(x).toPrecision(10));
const D=s=>{const m=/^(\d{4})-(\d\d)-(\d\d)$/.exec(s||"");if(!m)throw"Choose a valid date.";return new Date(Date.UTC(+m[1],m[2]-1,+m[3]))};
const ds=d=>d.toISOString().slice(0,10),dn=d=>d.toLocaleDateString("en-US",{weekday:"long",timeZone:"UTC"});
const ymd=(a,b)=>{if(b<a)throw"The end date is before the start date.";let y=b.getUTCFullYear()-a.getUTCFullYear(),m=b.getUTCMonth()-a.getUTCMonth(),d=b.getUTCDate()-a.getUTCDate();if(d<0){m--;d+=new Date(Date.UTC(b.getUTCFullYear(),b.getUTCMonth(),0)).getUTCDate()}if(m<0){y--;m+=12}return `${y} years, ${m} months, ${d} days`};
const lines=t=>t.split(/\r?\n/).map(x=>x.trim()).filter(x=>x);
const rnd=n=>{const b=new Uint32Array(1),lim=Math.floor(4294967296/n)*n;do crypto.getRandomValues(b);while(b[0]>=lim);return b[0]%n};
const TA=(id,l)=>({id,label:l,type:"textarea"}),SEL=(id,l,o)=>({id,label:l,type:"select",opts:o,def:o[0]});
const tx=fn=>({fields:[TA("t","Your text")],run:v=>{if(!v.t)throw"Enter some text first.";return fn(v.t)}});
const emi=(p,r,n)=>{const i=r/1200;return i===0?p/n:p*i*Math.pow(1+i,n)/(Math.pow(1+i,n)-1)};
const hx=s=>{s=s.trim().replace(/^#/,"");if(/^[0-9a-f]{3}$/i.test(s))s=[...s].map(c=>c+c).join("");if(!/^[0-9a-f]{6}$/i.test(s))throw"Enter a colour like #3ab7ff.";return[0,2,4].map(i=>parseInt(s.substr(i,2),16))};
const lum=([r,g,b])=>{const f=c=>{c/=255;return c<=.03928?c/12.92:Math.pow((c+.055)/1.055,2.4)};return .2126*f(r)+.7152*f(g)+.0722*f(b)};
const tm=s=>{if(!/^\d\d:\d\d$/.test(s||""))throw"Choose both times.";const[h,m]=s.split(":");return h*60+ +m};
const hm=m=>`${Math.floor(m/60)}h ${Math.round(m%60)}m`;
const csv=t=>{const rows=[];let r=[],c="",q=false;for(let i=0;i<t.length;i++){const ch=t[i];if(q){if(ch==='"'){if(t[i+1]==='"'){c+='"';i++}else q=false}else c+=ch}else if(ch==='"')q=true;else if(ch===","){r.push(c);c=""}else if(ch==="\n"||ch==="\r"){if(ch==="\r"&&t[i+1]==="\n")i++;r.push(c);rows.push(r);r=[];c=""}else c+=ch}if(c!==""||r.length){r.push(c);rows.push(r)}return rows.filter(x=>x.some(y=>y!==""))};
const ones="zero one two three four five six seven eight nine ten eleven twelve thirteen fourteen fifteen sixteen seventeen eighteen nineteen".split(" "),tens="  twenty thirty forty fifty sixty seventy eighty ninety".split(" ");
const W=n=>{if(n<20)return ones[n];if(n<100)return tens[n/10|0]+(n%10?"-"+ones[n%10]:"");if(n<1e3)return ones[n/100|0]+" hundred"+(n%100?" "+W(n%100):"");for(const[v,nm]of[[1e12,"trillion"],[1e9,"billion"],[1e6,"million"],[1e3,"thousand"]])if(n>=v)return W(Math.floor(n/v))+" "+nm+(n%v?" "+W(n%v):"")};
const RM=[[1000,"M"],[900,"CM"],[500,"D"],[400,"CD"],[100,"C"],[90,"XC"],[50,"L"],[40,"XL"],[10,"X"],[9,"IX"],[5,"V"],[4,"IV"],[1,"I"]];
const toR=n=>{let s="";for(const[v,r]of RM)while(n>=v){s+=r;n-=v}return s};
const b64=p=>{const s=p.replace(/-/g,"+").replace(/_/g,"/"),b=atob(s+"=".repeat((4-s.length%4)%4));return new TextDecoder().decode(Uint8Array.from(b,c=>c.charCodeAt(0)))};
const LOREM="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.".split(". ");
const SEP={"Comma":",","Space":" ","Semicolon":";","Tab":"\t","Pipe":"|"};
Object.assign(window.JT_TOOLS,{
"paragraph-counter":tx(t=>`Paragraphs: ${t.split(/\n\s*\n/).filter(x=>x.trim()).length}`),
"reading-time-calculator":tx(t=>{const w=t.trim().split(/\s+/).length;return `Words: ${w}\nSilent reading (200 wpm): ${(w/200).toFixed(1)} min\nSpeaking (130 wpm): ${(w/130).toFixed(1)} min`}),
"text-compare":{fields:[TA("a","Text A"),TA("b","Text B")],run:v=>{const a=lines(v.a),b=lines(v.b),A=new Set(a),B=new Set(b),oa=a.filter(x=>!B.has(x)),ob=b.filter(x=>!A.has(x));if(!oa.length&&!ob.length)return"The two texts have the same lines.";return `Only in A (${oa.length}):\n${oa.join("\n")||"-"}\n\nOnly in B (${ob.length}):\n${ob.join("\n")||"-"}`}},
"lorem-ipsum-generator":{fields:[{id:"n",label:"Paragraphs (1-20)",type:"number",def:3}],run:v=>{const n=num(v.n,"Paragraphs");if(!Number.isInteger(n)||n<1||n>20)throw"Choose 1 to 20 paragraphs.";return Array.from({length:n},()=>LOREM.join(". ")).join("\n\n")}},
"text-to-list":{fields:[TA("t","Text"),SEL("s","Split at",Object.keys(SEP).slice(0,4))],run:v=>{const l=v.t.split(SEP[v.s]).map(x=>x.trim()).filter(x=>x);if(!l.length)throw"Enter some text first.";return l.join("\n")}},
"list-to-text":{fields:[TA("t","List (one item per line)"),SEL("s","Join with",["Comma","Space","Semicolon","Pipe"])],run:v=>{const l=lines(v.t);if(!l.length)throw"Enter at least one item.";return l.join(v.s==="Comma"?", ":SEP[v.s])}},
"text-splitter":{fields:[TA("t","Text"),{id:"d",label:"Split at this text",type:"text",def:","}],run:v=>{if(!v.t||!v.d)throw"Enter the text and where to split it.";return v.t.split(v.d).join("\n")}},
"text-joiner":{fields:[TA("t","Lines to join"),{id:"j",label:"Join with",type:"text",def:", "}],run:v=>{const l=lines(v.t);if(!l.length)throw"Enter at least one line.";return l.join(v.j)}},
"date-difference-calculator":{fields:[{id:"a",label:"Start date",type:"date"},{id:"b",label:"End date",type:"date"}],run:v=>{const a=D(v.a),b=D(v.b);return `${ymd(a,b)}\nTotal days: ${Math.round((b-a)/864e5)}`}},
"percentage-increase-decrease":{fields:[{id:"a",label:"Old value",type:"number"},{id:"b",label:"New value",type:"number"}],run:v=>{const a=num(v.a,"Old value"),b=num(v.b,"New value");if(a===0)throw"Old value cannot be zero.";const p=(b-a)/Math.abs(a)*100;return `${fmt(Math.abs(p))}% ${p>=0?"increase":"decrease"}\nFormula: (new - old) / |old| × 100`}},
"loan-calculator":{fields:[{id:"p",label:"Loan amount",type:"number"},{id:"r",label:"Annual rate (%)",type:"number"},{id:"y",label:"Term (years)",type:"number"}],run:v=>{const p=num(v.p,"Loan amount"),r=num(v.r,"Rate"),y=num(v.y,"Term");if(p<=0||y<=0||r<0)throw"Loan amount and term must be above zero.";const n=y*12,e=emi(p,r,n);return `Monthly payment: ${e.toFixed(2)}\nTotal paid: ${(e*n).toFixed(2)}\nTotal interest: ${(e*n-p).toFixed(2)}\nInformational only.`}},
"ratio-calculator":{fields:[{id:"a",label:"First number",type:"number"},{id:"b",label:"Second number",type:"number"}],run:v=>{const a=num(v.a,"First number"),b=num(v.b,"Second number");if(a<0||b<0||(a===0&&b===0))throw"Enter positive numbers.";const x=Math.round(a*1e6),y=Math.round(b*1e6),g=(m,n)=>n?g(n,m%n):m,d=g(x,y);return `Ratio: ${x/d} : ${y/d}\nDecimal: ${b===0?"undefined":fmt(a/b)}`}},
"fraction-calculator":{fields:[{id:"a",label:"Numerator 1",type:"number",def:1},{id:"b",label:"Denominator 1",type:"number",def:2},SEL("o","Operation",["+","-","×","÷"]),{id:"c",label:"Numerator 2",type:"number",def:1},{id:"d",label:"Denominator 2",type:"number",def:3}],run:v=>{const[a,b,c,d]=["a","b","c","d"].map(k=>num(v[k],"Each value"));if(![a,b,c,d].every(Number.isInteger))throw"Use whole numbers only.";if(!b||!d)throw"Denominator cannot be zero.";let n,m;if(v.o==="+"){n=a*d+c*b;m=b*d}else if(v.o==="-"){n=a*d-c*b;m=b*d}else if(v.o==="×"){n=a*c;m=b*d}else{if(!c)throw"Cannot divide by zero.";n=a*d;m=b*c}const g=(x,y)=>y?g(y,x%y):Math.abs(x),k=g(n,m)||1;n/=k;m/=k;if(m<0){n=-n;m=-m}return `Result: ${m===1?n:n+"/"+m}\nDecimal: ${fmt(n/m)}`}},
"bmr-calculator":{fields:[SEL("s","Sex",["Male","Female"]),{id:"w",label:"Weight (kg)",type:"number"},{id:"h",label:"Height (cm)",type:"number"},{id:"a",label:"Age (years)",type:"number"}],run:v=>{const w=num(v.w,"Weight"),h=num(v.h,"Height"),a=num(v.a,"Age");if(w<=0||h<=0||a<=0)throw"All values must be above zero.";const b=10*w+6.25*h-5*a+(v.s==="Male"?5:-161);return `BMR: ${Math.round(b)} kcal/day\nFormula: Mifflin-St Jeor. This is an estimate, not medical advice.`}},
"time-duration-calculator":{fields:[{id:"s",label:"Start time",type:"time"},{id:"e",label:"End time",type:"time"}],run:v=>{const m=(tm(v.e)-tm(v.s)+1440)%1440;return `Duration: ${hm(m)} (${fmt(m/60)} hours)\nEnd times earlier than the start are treated as the next day.`}},
"work-hours-calculator":{fields:[{id:"s",label:"Start time",type:"time"},{id:"e",label:"End time",type:"time"},{id:"b",label:"Break (minutes)",type:"number",def:0},{id:"r",label:"Regular hours per day",type:"number",def:8}],run:v=>{const b=num(v.b,"Break"),r=num(v.r,"Regular hours");let m=(tm(v.e)-tm(v.s)+1440)%1440-b;if(b<0||m<0)throw"Break is longer than the shift.";const o=Math.max(0,m-r*60);return `Worked: ${hm(m)} (${fmt(m/60)} hours)\nOvertime: ${hm(o)}\nOvernight shifts are supported (22:00 to 06:00 = 8h).`}},
"date-add-subtract-calculator":{fields:[{id:"d",label:"Date",type:"date"},SEL("o","Action",["Add","Subtract"]),{id:"n",label:"Amount",type:"number",def:1},SEL("u","Unit",["Days","Weeks","Months","Years"])],run:v=>{const d=D(v.d);let n=num(v.n,"Amount");if(!Number.isInteger(n))throw"Amount must be a whole number.";if(v.o==="Subtract")n=-n;if(v.u==="Days")d.setUTCDate(d.getUTCDate()+n);else if(v.u==="Weeks")d.setUTCDate(d.getUTCDate()+7*n);else{const day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+(v.u==="Years"?12*n:n));d.setUTCDate(Math.min(day,new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate()))}return `${ds(d)} (${dn(d)})`}},
"age-at-date-calculator":{fields:[{id:"a",label:"Date of birth",type:"date"},{id:"b",label:"Age on this date",type:"date"}],run:v=>{const a=D(v.a),b=D(v.b);if(b<a)throw"The date is before the date of birth.";return `Age: ${ymd(a,b)}`}},
"number-to-words-converter":{fields:[{id:"n",label:"Number",type:"text"}],run:v=>{const s=v.n.trim();if(!/^-?\d+(\.\d+)?$/.test(s))throw"Enter a number like 1250 or -42.5.";const[i,f]=s.replace("-","").split(".");if(i.length>15)throw"Number is too large (max 15 digits).";return(s[0]==="-"?"minus ":"")+W(+i)+(f?" point "+[...f].map(x=>ones[x]).join(" "):"")}},
"overtime-calculator":{fields:[{id:"r",label:"Hourly rate",type:"number"},{id:"h",label:"Regular hours",type:"number"},{id:"o",label:"Overtime hours",type:"number"},{id:"m",label:"Overtime multiplier",type:"number",def:1.5}],run:v=>{const r=num(v.r,"Rate"),h=num(v.h,"Regular hours"),o=num(v.o,"Overtime hours"),m=num(v.m,"Multiplier");if(r<0||h<0||o<0||m<0)throw"Values cannot be negative.";return `Regular pay: ${(r*h).toFixed(2)}\nOvertime pay: ${(r*o*m).toFixed(2)}\nTotal: ${(r*h+r*o*m).toFixed(2)}\nOvertime rules differ by employer and region.`}},
"salary-calculator":{fields:[{id:"a",label:"Gross amount",type:"number"},SEL("p","Period",["Monthly","Annual"]),{id:"d",label:"Deductions (%)",type:"number",def:0}],run:v=>{const a=num(v.a,"Amount"),d=num(v.d,"Deductions");if(a<0||d<0||d>100)throw"Amount cannot be negative and deductions must be 0 to 100.";const y=v.p==="Monthly"?a*12:a;return `Annual gross: ${y.toFixed(2)}\nMonthly gross: ${(y/12).toFixed(2)}\nWeekly gross: ${(y/52).toFixed(2)}\nHourly gross (2080 h/yr): ${(y/2080).toFixed(2)}\nMonthly after ${d}% deductions: ${(y/12*(1-d/100)).toFixed(2)}\nEstimate only; not payroll advice.`}},
"number-base-converter":{fields:[{id:"v",label:"Value",type:"text"},SEL("f","From base",["10","2","8","16"]),SEL("t","To base",["2","8","10","16"])],run:v=>{const s=v.v.trim().toLowerCase(),f=+v.f,neg=s[0]==="-",d=neg?s.slice(1):s;if(!d)throw"Enter a value.";let n=0n;for(const c of d){const x="0123456789abcdef".indexOf(c);if(x<0||x>=f)throw`"${c}" is not valid in base ${f}.`;n=n*BigInt(f)+BigInt(x)}return(neg?"-":"")+n.toString(+v.t).toUpperCase()}},
"number-formatter":{fields:[{id:"n",label:"Number",type:"number"},SEL("l","Style",["en-US","en-IN","de-DE","fr-FR"]),{id:"d",label:"Decimals (0-10)",type:"number",def:2}],run:v=>{const n=num(v.n,"Number"),d=num(v.d,"Decimals");if(!Number.isInteger(d)||d<0||d>10)throw"Decimals must be 0 to 10.";return new Intl.NumberFormat(v.l,{minimumFractionDigits:d,maximumFractionDigits:d}).format(n)}},
"roman-numeral-converter":{fields:[{id:"v",label:"Number (1-3999) or Roman numeral",type:"text"}],run:v=>{const s=v.v.trim().toUpperCase();if(/^\d+$/.test(s)){const n=+s;if(n<1||n>3999)throw"Use a number from 1 to 3999.";return toR(n)}if(!/^[MDCLXVI]+$/.test(s))throw"Enter a number or a Roman numeral.";const m={M:1e3,D:500,C:100,L:50,X:10,V:5,I:1};let n=0;for(let i=0;i<s.length;i++){const a=m[s[i]],b=m[s[i+1]]||0;n+=a<b?-a:a}if(toR(n)!==s)throw"That is not a valid Roman numeral.";return String(n)}},
"random-choice-generator":{fields:[TA("t","Options (one per line)")],run:v=>{const l=lines(v.t);if(l.length<2)throw"Enter at least two options.";return l[rnd(l.length)]}},
"hash-generator":{fields:[TA("t","Text"),SEL("a","Algorithm",["SHA-256","SHA-1","SHA-384","SHA-512"])],run:async v=>{if(!v.t)throw"Enter some text first.";if(!(crypto&&crypto.subtle))throw"Hashing is not supported in this browser or needs HTTPS.";const h=await crypto.subtle.digest(v.a,new TextEncoder().encode(v.t));return[...new Uint8Array(h)].map(b=>b.toString(16).padStart(2,"0")).join("")}},
"strong-password-checker":{fields:[{id:"p",label:"Password (checked only in your browser, never sent or stored)",type:"password"}],run:v=>{const p=v.p;if(!p)throw"Enter a password to check.";const cl=[/[a-z]/,/[A-Z]/,/\d/,/[^\w]/].filter(r=>r.test(p)).length;let s=(p.length>=8)+(p.length>=12)+(p.length>=16)+cl;const bad=/password|123456|qwerty|letmein|admin|welcome|iloveyou/i.test(p),rep=/(.)\1{2,}/.test(p);if(bad)s-=3;if(rep)s-=1;const r=s<=2?"Weak":s<=4?"Fair":s<=6?"Strong":"Very strong",t=[];if(p.length<12)t.push("Use 12 or more characters.");if(cl<3)t.push("Mix upper, lower, numbers and symbols.");if(bad)t.push("Avoid common words and sequences.");if(rep)t.push("Avoid repeated characters.");return `Strength: ${r}\n${t.join("\n")||"No obvious weaknesses found."}\nThis is a simple estimate, not a guarantee.`}},
"jwt-decoder":{fields:[TA("t","JWT")],run:v=>{const p=v.t.trim().split(".");if(p.length!==3)throw"A JWT has three parts separated by dots.";let h,b;try{h=JSON.parse(b64(p[0]));b=JSON.parse(b64(p[1]))}catch(e){throw"Could not decode this token."}const e=b.exp?`\nExpires: ${new Date(b.exp*1e3).toISOString()}`:"";return `Header:\n${JSON.stringify(h,null,2)}\n\nPayload:\n${JSON.stringify(b,null,2)}${e}\n\nNOTE: Decoding is NOT verification. The signature was not checked, so do not treat this token as valid or trusted.`}},
"url-parser":{fields:[{id:"u",label:"URL",type:"text"}],run:v=>{let u;try{u=new URL(v.u.trim())}catch(e){throw"Enter a full URL such as https://example.com/path?x=1."}return `Protocol: ${u.protocol}\nHost: ${u.host}\nHostname: ${u.hostname}\nPort: ${u.port||"(default)"}\nPath: ${u.pathname}\nQuery: ${u.search||"(none)"}\nHash: ${u.hash||"(none)"}`}},
"query-string-parser":{fields:[{id:"q",label:"Query string or URL",type:"text"}],run:v=>{let s=v.q.trim();if(!s)throw"Enter a query string.";if(/^https?:/i.test(s)){try{s=new URL(s).search}catch(e){throw"That URL is not valid."}}const l=[...new URLSearchParams(s.replace(/^\?/,"")).entries()];if(!l.length)throw"No parameters found.";return l.map(([k,x])=>`${k} = ${x}`).join("\n")}},
"color-converter":{fields:[{id:"c",label:"Colour (#3ab7ff or rgb(58,183,255))",type:"text",def:"#3ab7ff"}],run:v=>{const s=v.c.trim(),m=/^rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)$/i.exec(s);let c=m?[+m[1],+m[2],+m[3]]:hx(s);if(c.some(x=>x>255))throw"RGB values must be 0 to 255.";const[r,g,b]=c.map(x=>x/255),M=Math.max(r,g,b),n=Math.min(r,g,b),d=M-n,l=(M+n)/2,S=d?d/(1-Math.abs(2*l-1)):0;let h=d?M===r?60*(((g-b)/d)%6):M===g?60*((b-r)/d+2):60*((r-g)/d+4):0;if(h<0)h+=360;return `HEX: #${c.map(x=>x.toString(16).padStart(2,"0")).join("")}\nRGB: rgb(${c.join(", ")})\nHSL: hsl(${Math.round(h)}, ${Math.round(S*100)}%, ${Math.round(l*100)}%)`}},
"regex-tester":{fields:[{id:"p",label:"Pattern (without slashes)",type:"text"},{id:"f",label:"Flags",type:"text",def:"g"},TA("t","Test text")],run:v=>{if(!v.p)throw"Enter a pattern.";let re;const f=[...new Set((v.f+"g").replace(/[^gimsuy]/g,""))].join("");try{re=new RegExp(v.p,f)}catch(e){throw"Invalid pattern: "+e.message}const m=[...v.t.matchAll(re)].slice(0,200);return m.length?`${m.length} match(es):\n`+m.map(x=>`#${x.index}: ${x[0]}`).join("\n"):"No matches."}},
"csv-to-json":{fields:[TA("t","CSV (first row = headers)")],run:v=>{const r=csv(v.t);if(r.length<2)throw"Enter a header row and at least one data row.";const h=r[0];return JSON.stringify(r.slice(1).map(x=>Object.fromEntries(h.map((k,i)=>[k,x[i]??""]))),null,2)}},
"json-to-csv":{fields:[TA("t","JSON (array of objects)")],run:v=>{let a;try{a=JSON.parse(v.t)}catch(e){throw"Invalid JSON: "+e.message}if(!Array.isArray(a))a=[a];if(!a.length||a.some(x=>x===null||typeof x!=="object"))throw"Provide an array of objects.";const h=[...new Set(a.flatMap(Object.keys))],q=x=>{x=x==null?"":typeof x==="object"?JSON.stringify(x):String(x);return/[",\n\r]/.test(x)?'"'+x.replace(/"/g,'""')+'"':x};return[h.map(q).join(","),...a.map(o=>h.map(k=>q(o[k])).join(","))].join("\n")}},
"contrast-checker":{fields:[{id:"f",label:"Text colour",type:"color",def:"#ffffff"},{id:"b",label:"Background colour",type:"color",def:"#05080f"}],run:v=>{const a=lum(hx(v.f)),b=lum(hx(v.b)),r=(Math.max(a,b)+.05)/(Math.min(a,b)+.05),y=x=>x?"Pass":"Fail";return `Contrast ratio: ${r.toFixed(2)}:1\nAA normal text (4.5): ${y(r>=4.5)}\nAA large text (3): ${y(r>=3)}\nAAA normal text (7): ${y(r>=7)}\nAAA large text (4.5): ${y(r>=4.5)}`}},
"hex-color-generator":{fields:[{id:"n",label:"How many (1-20)",type:"number",def:5}],run:v=>{const n=num(v.n,"Count");if(!Number.isInteger(n)||n<1||n>20)throw"Choose 1 to 20.";return Array.from({length:n},()=>"#"+[0,0,0].map(()=>rnd(256).toString(16).padStart(2,"0")).join("")).join("\n")}},
"split-bill-calculator":{fields:[{id:"t",label:"Bill total",type:"number"},{id:"n",label:"People",type:"number",def:2},{id:"p",label:"Tip (%)",type:"number",def:0}],run:v=>{const t=num(v.t,"Bill"),n=num(v.n,"People"),p=num(v.p,"Tip");if(t<0||p<0||!Number.isInteger(n)||n<1)throw"Bill and tip cannot be negative; people must be a whole number of 1 or more.";const a=t*(1+p/100);return `Total with tip: ${a.toFixed(2)}\nEach person pays: ${(a/n).toFixed(2)}`}},
"attendance-calculator":{fields:[{id:"t",label:"Total working days",type:"number"},{id:"p",label:"Days present",type:"number"}],run:v=>{const t=num(v.t,"Total days"),p=num(v.p,"Days present");if(t<=0||p<0||p>t)throw"Total must be above zero and present days cannot exceed it.";return `Present: ${p}\nAbsent: ${t-p}\nAttendance: ${fmt(p/t*100)}%`}},
"leave-days-calculator":{fields:[{id:"a",label:"Start date",type:"date"},{id:"b",label:"End date",type:"date"},{id:"w",label:"Exclude weekends (Sat, Sun)",type:"checkbox",def:true},TA("h","Holidays to exclude (YYYY-MM-DD, one per line, optional)")],run:v=>{const a=D(v.a),b=D(v.b);if(b<a)throw"The end date is before the start date.";const t=Math.round((b-a)/864e5)+1;if(t>3660)throw"Choose a range under 10 years.";const H=new Set(lines(v.h).map(x=>ds(D(x))));let n=0;for(let i=0;i<t;i++){const d=new Date(a.getTime()+i*864e5),w=d.getUTCDay();if(v.w&&(w===0||w===6))continue;if(H.has(ds(d)))continue;n++}return `Leave days: ${n}\nCalendar days in range: ${t}`}}
});})();
(function(){
const num=(x,n)=>{if(x===""||x==null||isNaN(x))throw n+" must be a number.";return +x},fmt=x=>String(+Number(x).toPrecision(10));
const lines=t=>t.split(/\r?\n/),rnd=n=>{const b=new Uint32Array(1),lim=Math.floor(4294967296/n)*n;do crypto.getRandomValues(b);while(b[0]>=lim);return b[0]%n};
const TA=(id,l)=>({id,label:l,type:"textarea"}),SEL=(id,l,o)=>({id,label:l,type:"select",opts:o,def:o[0]}),N=(id,l,d)=>({id,label:l,type:"number",def:d});
const tx=fn=>({fields:[TA("t","Your text")],run:v=>{if(!v.t)throw"Enter some text first.";return fn(v.t)}});
const conv=U=>{const k=Object.keys(U);return{fields:[N("v","Value",1),SEL("f","From",k),{...SEL("t","To",k),def:k[1]}],run:v=>{const n=num(v.v,"Value");return `${fmt(n)} ${v.f} = ${fmt(n*U[v.f]/U[v.t])} ${v.t}`}}};
const hx=s=>{s=s.trim().replace(/^#/,"");if(/^[0-9a-f]{3}$/i.test(s))s=[...s].map(c=>c+c).join("");if(!/^[0-9a-f]{6}$/i.test(s))throw"Enter a colour like #3ab7ff.";return[0,2,4].map(i=>parseInt(s.substr(i,2),16))};
const hex=c=>"#"+c.map(x=>x.toString(16).padStart(2,"0")).join("");
const hsl=c=>{const[r,g,b]=c.map(x=>x/255),M=Math.max(r,g,b),n=Math.min(r,g,b),d=M-n,l=(M+n)/2,S=d?d/(1-Math.abs(2*l-1)):0;let h=d?M===r?60*(((g-b)/d)%6):M===g?60*((b-r)/d+2):60*((r-g)/d+4):0;if(h<0)h+=360;return `hsl(${Math.round(h)}, ${Math.round(S*100)}%, ${Math.round(l*100)}%)`};
const rgbIn=v=>["r","g","b"].map(k=>{const x=num(v[k],k.toUpperCase());if(!Number.isInteger(x)||x<0||x>255)throw"RGB values must be whole numbers from 0 to 255.";return x});
const RGB=[N("r","Red (0-255)"),N("g","Green (0-255)"),N("b","Blue (0-255)")];
const words=t=>t.match(/[\p{L}\p{N}]+/gu)||[];
const b64e=t=>{let s="";new TextEncoder().encode(t).forEach(b=>s+=String.fromCharCode(b));return btoa(s)};
const seg=t=>window.Intl&&Intl.Segmenter?[...new Intl.Segmenter().segment(t)].map(x=>x.segment):[...t];
const D=s=>{const m=/^(\d{4})-(\d\d)-(\d\d)$/.exec(s||"");if(!m)throw"Choose a valid date.";return new Date(Date.UTC(+m[1],m[2]-1,+m[3]))};
const ymd=(a,b)=>{let y=b.getUTCFullYear()-a.getUTCFullYear(),m=b.getUTCMonth()-a.getUTCMonth(),d=b.getUTCDate()-a.getUTCDate();if(d<0){m--;d+=new Date(Date.UTC(b.getUTCFullYear(),b.getUTCMonth(),0)).getUTCDate()}if(m<0){y--;m+=12}return `${y} years, ${m} months, ${d} days`};
const bmr=(s,w,h,a)=>10*w+6.25*h-5*a+(s==="Male"?5:-161);
const A="swift bright calm bold clever quiet rapid lucky brave silent cosmic golden".split(" "),Nn="falcon river comet tiger pixel forest ember harbor orbit maple raven summit".split(" ");
Object.assign(window.JT_TOOLS,{
"character-counter":tx(t=>`Characters (with spaces): ${[...t].length}\nCharacters (no spaces): ${[...t.replace(/\s/g,"")].length}`),
"sentence-counter":tx(t=>`Sentences: ${(t.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[]).filter(x=>x.trim()).length}`),
"text-case-converter":{fields:[TA("t","Your text"),SEL("c","Convert to",["UPPERCASE","lowercase","Title Case","Sentence case","camelCase","snake_case","kebab-case"])],run:v=>{const t=v.t;if(!t)throw"Enter some text first.";const w=words(t).map(x=>x.toLowerCase()),cap=x=>x.charAt(0).toUpperCase()+x.slice(1);switch(v.c){case"UPPERCASE":return t.toUpperCase();case"lowercase":return t.toLowerCase();case"Title Case":return t.toLowerCase().replace(/(^|\s)(\p{L})/gu,(m,a,b)=>a+b.toUpperCase());case"Sentence case":return t.toLowerCase().replace(/(^\s*|[.!?]\s+)(\p{L})/gu,(m,a,b)=>a+b.toUpperCase());case"camelCase":return w.map((x,i)=>i?cap(x):x).join("");case"snake_case":return w.join("_");default:return w.join("-")}}},
"remove-extra-spaces":tx(t=>lines(t).map(l=>l.replace(/[ \t]+/g," ").trim()).join("\n").trim()),
"remove-empty-lines":tx(t=>lines(t).filter(l=>l.trim()).join("\n")),
"remove-duplicate-lines":tx(t=>{const l=lines(t),u=[...new Set(l)];return u.join("\n")+`\n\n(${l.length-u.length} duplicate line(s) removed)`}),
"reverse-text":tx(t=>seg(t).reverse().join("")),
"find-replace":{fields:[TA("t","Your text"),{id:"a",label:"Find",type:"text"},{id:"b",label:"Replace with",type:"text"},{id:"c",label:"Match case",type:"checkbox"}],run:v=>{if(!v.t||!v.a)throw"Enter the text and what to find.";const re=new RegExp(v.a.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),v.c?"g":"gi"),n=(v.t.match(re)||[]).length;if(!n)throw"Nothing matched.";return v.t.replace(re,()=>v.b)+`\n\n(${n} replacement(s))`}},
"age-calculator":{fields:[{id:"a",label:"Date of birth",type:"date"}],run:v=>{const a=D(v.a),n=new Date(),t=new Date(Date.UTC(n.getFullYear(),n.getMonth(),n.getDate()));if(a>t)throw"Date of birth is in the future.";return `Age: ${ymd(a,t)}\nTotal days: ${Math.round((t-a)/864e5)}`}},
"discount-calculator":{fields:[N("p","Original price"),N("d","Discount (%)")],run:v=>{const p=num(v.p,"Price"),d=num(v.d,"Discount");if(p<0||d<0||d>100)throw"Price cannot be negative and discount must be 0 to 100.";return `You save: ${(p*d/100).toFixed(2)}\nFinal price: ${(p*(1-d/100)).toFixed(2)}`}},
"gst-calculator":{fields:[N("a","Amount"),N("r","GST rate (%)",18),SEL("m","Mode",["Add GST","Remove GST"])],run:v=>{const a=num(v.a,"Amount"),r=num(v.r,"Rate");if(a<0||r<0)throw"Values cannot be negative.";const n=v.m==="Add GST"?a:a/(1+r/100),g=n*r/100;return `Net amount: ${n.toFixed(2)}\nGST (${r}%): ${g.toFixed(2)}\nGross amount: ${(n+g).toFixed(2)}\nInformational only; check with your accountant.`}},
"profit-loss-calculator":{fields:[N("c","Cost price"),N("s","Selling price")],run:v=>{const c=num(v.c,"Cost"),s=num(v.s,"Selling price");if(c<=0||s<0)throw"Cost must be above zero and selling price cannot be negative.";const d=s-c;return `${d>=0?"Profit":"Loss"}: ${Math.abs(d).toFixed(2)}\n${d>=0?"Profit":"Loss"} %: ${fmt(Math.abs(d)/c*100)}%`}},
"tip-calculator":{fields:[N("t","Bill amount"),N("p","Tip (%)",10),N("n","People",1)],run:v=>{const t=num(v.t,"Bill"),p=num(v.p,"Tip"),n=num(v.n,"People");if(t<0||p<0||!Number.isInteger(n)||n<1)throw"Check your values: people must be a whole number of 1 or more.";const tip=t*p/100;return `Tip: ${tip.toFixed(2)}\nTotal: ${(t+tip).toFixed(2)}\nPer person: ${((t+tip)/n).toFixed(2)}`}},
"bmi-calculator":{fields:[N("w","Weight (kg)"),N("h","Height (cm)")],run:v=>{const w=num(v.w,"Weight"),h=num(v.h,"Height");if(w<=0||h<=0)throw"Weight and height must be above zero.";const b=w/Math.pow(h/100,2);return `BMI: ${b.toFixed(1)} (${b<18.5?"Underweight":b<25?"Normal":b<30?"Overweight":"Obese"} by adult WHO ranges)\nInformational only, not medical advice.`}},
"calorie-calculator":{fields:[SEL("s","Sex",["Male","Female"]),N("w","Weight (kg)"),N("h","Height (cm)"),N("a","Age (years)"),SEL("l","Activity",["Sedentary (1.2)","Light (1.375)","Moderate (1.55)","Very active (1.725)"])],run:v=>{const w=num(v.w,"Weight"),h=num(v.h,"Height"),a=num(v.a,"Age");if(w<=0||h<=0||a<=0)throw"All values must be above zero.";const b=bmr(v.s,w,h,a),f=+v.l.match(/\(([\d.]+)\)/)[1];return `BMR: ${Math.round(b)} kcal/day\nMaintenance calories: ${Math.round(b*f)} kcal/day\nEstimate only, not medical or dietary advice.`}},
"length-converter":conv({mm:.001,cm:.01,m:1,km:1e3,inch:.0254,foot:.3048,yard:.9144,mile:1609.344}),
"weight-converter":conv({mg:1e-6,g:.001,kg:1,tonne:1e3,oz:.028349523125,lb:.45359237,stone:6.35029318}),
"time-converter":conv({ms:.001,second:1,minute:60,hour:3600,day:86400,week:604800,"year (365 d)":31536e3}),
"data-storage-converter":conv({Byte:1,"KB (1000)":1e3,"MB (1000²)":1e6,"GB (1000³)":1e9,"TB (1000⁴)":1e12,"KiB (1024)":1024,"MiB (1024²)":1048576,"GiB (1024³)":1073741824,"TiB (1024⁴)":1099511627776}),
"temperature-converter":{fields:[N("v","Value",0),SEL("f","From",["°C","°F","K"]),{...SEL("t","To",["°C","°F","K"]),def:"°F"}],run:v=>{const n=num(v.v,"Value"),c=v.f==="°C"?n:v.f==="°F"?(n-32)*5/9:n-273.15;if(c<-273.15-1e-9)throw"That is below absolute zero.";const o=v.t==="°C"?c:v.t==="°F"?c*9/5+32:c+273.15;return `${fmt(n)} ${v.f} = ${fmt(o)} ${v.t}`}},
"pin-generator":{fields:[N("n","Digits (4-12)",6)],run:v=>{const n=num(v.n,"Digits");if(!Number.isInteger(n)||n<4||n>12)throw"Choose 4 to 12 digits.";return Array.from({length:n},()=>rnd(10)).join("")}},
"random-number-generator":{fields:[N("a","Minimum",1),N("b","Maximum",100),N("c","How many (1-100)",1)],run:v=>{const a=num(v.a,"Minimum"),b=num(v.b,"Maximum"),c=num(v.c,"Count");if(![a,b,c].every(Number.isInteger))throw"Use whole numbers.";if(a>b)throw"Minimum cannot be above maximum.";if(c<1||c>100)throw"Choose 1 to 100 numbers.";if(b-a+1>4294967296)throw"Range is too large.";return Array.from({length:c},()=>a+rnd(b-a+1)).join("\n")}},
"username-generator":{fields:[N("n","How many (1-20)",5)],run:v=>{const n=num(v.n,"Count");if(!Number.isInteger(n)||n<1||n>20)throw"Choose 1 to 20.";return Array.from({length:n},()=>A[rnd(A.length)]+Nn[rnd(Nn.length)]+rnd(1000)).join("\n")}},
"uuid-generator":{fields:[N("n","How many (1-20)",1)],run:v=>{const n=num(v.n,"Count");if(!Number.isInteger(n)||n<1||n>20)throw"Choose 1 to 20.";const u=()=>{if(crypto.randomUUID)return crypto.randomUUID();const b=crypto.getRandomValues(new Uint8Array(16));b[6]=b[6]&15|64;b[8]=b[8]&63|128;const h=[...b].map(x=>x.toString(16).padStart(2,"0")).join("");return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`};return Array.from({length:n},u).join("\n")}},
"base64-encoder":tx(b64e),
"base64-decoder":tx(t=>{try{const s=atob(t.trim().replace(/-/g,"+").replace(/_/g,"/"));return new TextDecoder("utf-8",{fatal:true}).decode(Uint8Array.from(s,c=>c.charCodeAt(0)))}catch(e){throw"This is not valid Base64 text."}}),
"json-validator":{fields:[TA("t","JSON")],run:v=>{if(!v.t.trim())throw"Paste some JSON first.";let o;try{o=JSON.parse(v.t)}catch(e){throw"Invalid JSON: "+e.message}return `Valid JSON. Top level: ${Array.isArray(o)?`array with ${o.length} item(s)`:o&&typeof o==="object"?`object with ${Object.keys(o).length} key(s)`:typeof o}`}},
"json-minifier":{fields:[TA("t","JSON")],run:v=>{if(!v.t.trim())throw"Paste some JSON first.";try{return JSON.stringify(JSON.parse(v.t))}catch(e){throw"Invalid JSON: "+e.message}}},
"json-viewer":{fields:[TA("t","JSON")],run:v=>{if(!v.t.trim())throw"Paste some JSON first.";let o;try{o=JSON.parse(v.t)}catch(e){throw"Invalid JSON: "+e.message}const out=[];const w=(x,p)=>{if(out.length>=500)return;if(x&&typeof x==="object")Object.keys(x).forEach(k=>w(x[k],p?p+(Array.isArray(x)?`[${k}]`:"."+k):Array.isArray(x)?`[${k}]`:k));else out.push(`${p||"(value)"} : ${JSON.stringify(x)}`)};w(o,"");return out.join("\n")+(out.length>=500?"\n… (first 500 values shown)":"")}},
"hex-to-rgb":{fields:[{id:"c",label:"HEX colour",type:"text",def:"#3ab7ff"}],run:v=>`rgb(${hx(v.c).join(", ")})`},
"rgb-to-hex":{fields:RGB,run:v=>hex(rgbIn(v))},
"rgb-to-hsl":{fields:RGB,run:v=>hsl(rgbIn(v))},
"unix-timestamp-converter":{fields:[{id:"u",label:"Unix timestamp (seconds or ms)",type:"text"},{id:"d",label:"or a date/time (e.g. 2026-01-31T10:00:00Z)",type:"text"}],run:v=>{const u=v.u.trim(),s=v.d.trim();if(!u&&!s)throw"Fill in one of the two fields.";if(u){if(!/^-?\d+$/.test(u))throw"Timestamp must be whole digits.";const n=+u,d=new Date(Math.abs(n)>=1e11?n:n*1e3);if(isNaN(d))throw"Timestamp is out of range.";return `${d.toISOString()} (UTC)`}const d=new Date(s);if(isNaN(d))throw"Could not read that date.";return `Seconds: ${Math.floor(d/1e3)}\nMilliseconds: ${d.getTime()}`}},
"user-agent-parser":{fields:[TA("t","User agent string (leave blank to use this browser)")],run:v=>{const u=v.t.trim()||navigator.userAgent,b=/Edg\//.test(u)?"Edge":/OPR\/|Opera/.test(u)?"Opera":/Firefox\//.test(u)?"Firefox":/Chrome\//.test(u)?"Chrome":/Safari\//.test(u)?"Safari":"Unknown",o=/Windows/.test(u)?"Windows":/Android/.test(u)?"Android":/iPhone|iPad|iOS/.test(u)?"iOS":/Mac OS X/.test(u)?"macOS":/Linux/.test(u)?"Linux":"Unknown",m=(u.match(/(?:Edg|OPR|Firefox|Chrome|Version)\/([\d.]+)/)||[])[1]||"unknown";return `Browser: ${b} ${m}\nOperating system: ${o}\nDevice type: ${/Mobi|Android|iPhone/.test(u)?"Mobile":"Desktop or tablet"}\nThis is an approximation from the text supplied.`}},
"color-picker":{fields:[{id:"c",label:"Pick a colour",type:"color",def:"#3ab7ff"}],run:v=>{const c=hx(v.c);return `HEX: ${hex(c)}\nRGB: rgb(${c.join(", ")})\n${hsl(c)}`}},
"random-color-generator":{fields:[N("n","How many (1-20)",5)],run:v=>{const n=num(v.n,"Count");if(!Number.isInteger(n)||n<1||n>20)throw"Choose 1 to 20.";return Array.from({length:n},()=>{const c=[0,0,0].map(()=>rnd(256));return `${hex(c)}  rgb(${c.join(", ")})`}).join("\n")}}
});})();
(function(){
const num=(x,n)=>{if(x===""||x==null||isNaN(x))throw n+" must be a number.";return +x},fmt=x=>String(+Number(x).toPrecision(10));
const TA=(id,l)=>({id,label:l,type:"textarea"}),SEL=(id,l,o,d)=>({id,label:l,type:"select",opts:o,def:d||o[0]}),N=(id,l,d)=>({id,label:l,type:"number",def:d}),C=(id,l,d)=>({id,label:l,type:"color",def:d});
const h=(t,a={},...c)=>{const e=document.createElement(t);for(const k in a){if(k==="class")e.className=a[k];else if(k.slice(0,2)==="on")e.addEventListener(k.slice(2),a[k]);else e.setAttribute(k,a[k])}e.append(...c);return e};
const hx=s=>{s=String(s).trim().replace(/^#/,"");if(!/^[0-9a-f]{6}$/i.test(s))throw"Pick a valid colour.";return[0,2,4].map(i=>parseInt(s.substr(i,2),16))};
const hex=c=>"#"+c.map(x=>Math.round(x).toString(16).padStart(2,"0")).join("");
const rgba=(c,a)=>`rgba(${hx(c).join(",")},${a})`;
const toHsl=([r,g,b])=>{r/=255;g/=255;b/=255;const M=Math.max(r,g,b),n=Math.min(r,g,b),d=M-n,l=(M+n)/2,s=d?d/(1-Math.abs(2*l-1)):0;let H=d?M===r?60*(((g-b)/d)%6):M===g?60*((b-r)/d+2):60*((r-g)/d+4):0;if(H<0)H+=360;return[H,s,l]};
const fromHsl=(H,s,l)=>{H=((H%360)+360)%360;const k=n=>(n+H/30)%12,a=s*Math.min(l,1-l),f=n=>l-a*Math.max(-1,Math.min(k(n)-3,Math.min(9-k(n),1)));return[f(0)*255,f(8)*255,f(4)*255]};
const lines=t=>t.split(/\r?\n/).map(x=>x.trim()).filter(x=>x),money=x=>x.toFixed(2);
const pv=(el,fn)=>{el.textContent="";const b=h("div",{class:"pv"});fn(b);el.append(b)};
const int=(x,n,a,b)=>{const v=num(x,n);if(!Number.isInteger(v)||v<a||v>b)throw`${n} must be a whole number from ${a} to ${b}.`;return v};
const tp=(f)=>({fields:[TA("t","Your code")],run:v=>{if(!v.t.trim())throw"Paste some code first.";return f(v.t)}});
const cssMin=t=>t.replace(/\/\*[\s\S]*?\*\//g,"").replace(/\s+/g," ").replace(/\s*([{}:;,>])\s*/g,"$1").replace(/;}/g,"}").trim();
const cssFmt=t=>{t=t.replace(/\/\*[\s\S]*?\*\//g,"").replace(/\s+/g," ");let o="",i=0,q=null;for(const c of t){if(q){o+=c;if(c===q)q=null}else if(c==='"'||c==="'"){q=c;o+=c}else if(c==="{"){o=o.trimEnd()+" {\n"+"  ".repeat(++i)}else if(c==="}"){i=Math.max(0,i-1);o=o.trimEnd()+"\n"+"  ".repeat(i)+"}\n"+"  ".repeat(i)}else if(c===";")o+=";\n"+"  ".repeat(i);else o+=c}return o.split("\n").map(l=>l.trimEnd()).filter(l=>l.trim()).join("\n")};
const VOID=/^<(area|base|br|col|embed|hr|img|input|link|meta|source|track|wbr)\b/i;
const htmlChk=t=>{if(/<(pre|textarea)\b/i.test(t))throw"This HTML contains <pre> or <textarea>. Changing whitespace there could alter it, so it was left untouched."};
const keyLog=[];
Object.assign(window.JT_TOOLS,{
"aspect-ratio-calculator":{fields:[N("w","Width",1920),N("h","Height",1080),N("n","New width (optional, to find the matching height)")],run:v=>{const w=num(v.w,"Width"),H=num(v.h,"Height");if(w<=0||H<=0)throw"Width and height must be above zero.";const g=(a,b)=>b?g(b,a%b):a,d=g(Math.round(w),Math.round(H));let o=`Aspect ratio: ${Math.round(w)/d}:${Math.round(H)/d}\nDecimal: ${fmt(w/H)}`;if(v.n!==""){const n=num(v.n,"New width");if(n<=0)throw"New width must be above zero.";o+=`\nHeight for width ${fmt(n)}: ${fmt(n*H/w)}`}return o}},
"screen-resolution-checker":{fields:[],run:()=>`Screen: ${screen.width} × ${screen.height}\nViewport: ${innerWidth} × ${innerHeight}\nDevice pixel ratio: ${devicePixelRatio}\nColour depth: ${screen.colorDepth}-bit\nOrientation: ${screen.orientation?screen.orientation.type:"not reported"}`},
"browser-information":{fields:[],run:()=>{const n=navigator;return `User agent: ${n.userAgent}\nLanguage: ${n.language}\nLanguages: ${(n.languages||[]).join(", ")}\nCookies enabled: ${n.cookieEnabled}\nOnline: ${n.onLine}\nLogical CPU cores: ${n.hardwareConcurrency||"not reported"}\nFeatures: ${[["Service Worker","serviceWorker"],["Clipboard","clipboard"],["Web Share","share"],["Media devices","mediaDevices"],["Geolocation","geolocation"]].map(([a,b])=>`${a} ${b in n?"yes":"no"}`).join(", ")}`}},
"device-information":{fields:[],run:()=>{const n=navigator;return `Platform (as reported): ${n.platform||"not reported"}\nScreen: ${screen.width} × ${screen.height} at ${devicePixelRatio}x\nViewport: ${innerWidth} × ${innerHeight}\nTouch points: ${n.maxTouchPoints||0}\nApprox. memory: ${n.deviceMemory?n.deviceMemory+" GB":"not reported"}\nLanguage: ${n.language}\nTime zone: ${Intl.DateTimeFormat().resolvedOptions().timeZone}\nOnly information your browser exposes is shown.`}},
"online-offline-detector":{fields:[],run:()=>`Browser reports: ${navigator.onLine?"Online":"Offline"}\nThis shows whether your device has a network connection, not whether a specific website is reachable.`},
"battery-information":{fields:[],run:async()=>{if(!navigator.getBattery)throw"Battery information is not available in this browser.";const b=await navigator.getBattery();return `Level: ${Math.round(b.level*100)}%\nCharging: ${b.charging?"yes":"no"}\nTime to full: ${isFinite(b.chargingTime)?Math.round(b.chargingTime/60)+" min":"n/a"}\nTime to empty: ${isFinite(b.dischargingTime)?Math.round(b.dischargingTime/60)+" min":"n/a"}`}},
"network-information":{fields:[],run:()=>{const c=navigator.connection;if(!c)throw"Network information is not supported by this browser.";return `Type: ${c.effectiveType||"n/a"}\nEstimated downlink: ${c.downlink??"n/a"} Mbps\nEstimated round-trip: ${c.rtt??"n/a"} ms\nData saver: ${c.saveData?"on":"off"}\nThese are browser estimates, not a speed test.`}},
"invoice-calculator":{fields:[TA("t","Items (one per line: description, quantity, unit price)"),N("d","Discount (%)",0),N("x","Tax (%)",0)],run:v=>{const l=lines(v.t);if(!l.length)throw"Add at least one item.";let s=0;const o=l.map((x,i)=>{const p=x.split(",").map(y=>y.trim());if(p.length<3)throw`Line ${i+1}: use "description, quantity, price".`;const q=num(p[p.length-2],`Line ${i+1} quantity`),u=num(p[p.length-1],`Line ${i+1} price`);if(q<0||u<0)throw`Line ${i+1}: values cannot be negative.`;s+=q*u;return `${p.slice(0,-2).join(",")}: ${fmt(q)} × ${money(u)} = ${money(q*u)}`});const d=num(v.d,"Discount"),x=num(v.x,"Tax");if(d<0||d>100||x<0)throw"Discount must be 0 to 100 and tax cannot be negative.";const a=s*(1-d/100),tax=a*x/100;return o.join("\n")+`\n\nSubtotal: ${money(s)}\nDiscount: -${money(s-a)}\nTax: ${money(tax)}\nTotal: ${money(a+tax)}`}},
"expense-calculator":{fields:[TA("t","Expenses (one per line: name, amount)")],run:v=>{const l=lines(v.t);if(!l.length)throw"Add at least one expense.";const a=l.map((x,i)=>{const p=x.split(","),n=num(p[p.length-1].trim(),`Line ${i+1} amount`);return[p.slice(0,-1).join(",").trim()||"Item",n]});const t=a.reduce((s,x)=>s+x[1],0),m=a.reduce((b,x)=>x[1]>b[1]?x:b);return `Items: ${a.length}\nTotal: ${money(t)}\nAverage: ${money(t/a.length)}\nHighest: ${m[0]} (${money(m[1])})`}},
"payslip-calculator":{fields:[N("b","Basic salary"),N("a","Allowances",0),N("o","Overtime pay",0),N("u","Bonus",0),N("d","Deductions",0)],run:v=>{const[b,a,o,u,d]=["b","a","o","u","d"].map(k=>num(v[k],"Each value"));if([b,a,o,u,d].some(x=>x<0))throw"Values cannot be negative.";const g=b+a+o+u;if(d>g)throw"Deductions exceed gross pay.";return `Gross pay: ${money(g)}\nDeductions: ${money(d)}\nNet pay: ${money(g-d)}\nUses only the figures you enter; it applies no payroll rules or taxes.`}},
"color-palette-generator":{fields:[C("c","Base colour","#2563ff"),SEL("m","Palette",["Complementary","Analogous","Triadic","Tetradic","Monochrome"])],run:v=>{const[H,s,l]=toHsl(hx(v.c)),d={Complementary:[0,180],Analogous:[-30,0,30],Triadic:[0,120,240],Tetradic:[0,90,180,270]}[v.m],p=d?d.map(x=>hex(fromHsl(H+x,s,l))):[.2,.35,.5,.65,.8].map(x=>hex(fromHsl(H,s,x)));v._p=p;return p.join("\n")},preview:(v,el)=>pv(el,b=>{b.className="sw";v._p.forEach(c=>{const i=h("i");i.style.background=c;b.append(i)})})},
"gradient-generator":{fields:[C("a","Start colour","#2563ff"),C("b","End colour","#06d6ff"),N("g","Angle (0-360)",135)],run:v=>{const g=int(v.g,"Angle",0,360);v._c=`linear-gradient(${g}deg, ${hex(hx(v.a))}, ${hex(hx(v.b))})`;return `background: ${v._c};`},preview:(v,el)=>pv(el,b=>{b.style.background=v._c;b.style.height="120px";b.style.borderRadius="14px"})},
"css-gradient-generator":{fields:[SEL("k","Type",["linear","radial"]),C("a","Colour 1","#2563ff"),C("b","Colour 2","#8b5cf6"),C("c","Colour 3","#06d6ff"),N("g","Angle (linear only)",90)],run:v=>{const g=int(v.g,"Angle",0,360),s=[v.a,v.b,v.c].map(x=>hex(hx(x))).join(", ");v._c=v.k==="linear"?`linear-gradient(${g}deg, ${s})`:`radial-gradient(circle, ${s})`;return `background: ${v._c};`},preview:(v,el)=>pv(el,b=>{b.style.background=v._c;b.style.height="120px";b.style.borderRadius="14px"})},
"css-box-shadow-generator":{fields:[N("x","Horizontal offset (px)",0),N("y","Vertical offset (px)",8),N("b","Blur (px)",24),N("s","Spread (px)",0),C("c","Colour","#000000"),N("o","Opacity (0-100)",35),{id:"i",label:"Inset",type:"checkbox"}],run:v=>{const[x,y,b,s]=["x","y","b","s"].map(k=>num(v[k],k)),o=num(v.o,"Opacity");if(b<0||o<0||o>100)throw"Blur cannot be negative and opacity must be 0 to 100.";v._c=`${v.i?"inset ":""}${x}px ${y}px ${b}px ${s}px ${rgba(v.c,o/100)}`;return `box-shadow: ${v._c};`},preview:(v,el)=>pv(el,b=>{b.style.boxShadow=v._c;b.style.borderRadius="14px";b.style.background="var(--card)"})},
"css-border-radius-generator":{fields:[N("a","Top left (px)",16),N("b","Top right (px)",16),N("c","Bottom right (px)",16),N("d","Bottom left (px)",16)],run:v=>{const r=["a","b","c","d"].map(k=>{const x=num(v[k],"Radius");if(x<0)throw"Radius cannot be negative.";return x+"px"}).join(" ");v._c=r;return `border-radius: ${r};`},preview:(v,el)=>pv(el,b=>{b.style.borderRadius=v._c;b.style.background="linear-gradient(135deg,#2563ff,#06d6ff)";b.style.height="120px"})},
"css-text-shadow-generator":{fields:[{id:"t",label:"Preview text",type:"text",def:"Jadon Tools"},N("x","Horizontal offset (px)",2),N("y","Vertical offset (px)",2),N("b","Blur (px)",6),C("c","Colour","#06d6ff")],run:v=>{const x=num(v.x,"X"),y=num(v.y,"Y"),b=num(v.b,"Blur");if(b<0)throw"Blur cannot be negative.";v._c=`${x}px ${y}px ${b}px ${hex(hx(v.c))}`;return `text-shadow: ${v._c};`},preview:(v,el)=>pv(el,b=>{b.style.textShadow=v._c;b.style.font="800 2rem system-ui";b.textContent=v.t||"Text"})},
"css-button-generator":{fields:[{id:"t",label:"Button text",type:"text",def:"Click me"},C("b","Background","#2563ff"),C("c","Text colour","#ffffff"),N("r","Corner radius (px)",12),N("p","Padding (px)",14),N("f","Font size (px)",16)],run:v=>{const r=num(v.r,"Radius"),p=num(v.p,"Padding"),f=num(v.f,"Font size");if(r<0||p<0||f<8)throw"Check your values.";v._s={background:hex(hx(v.b)),color:hex(hx(v.c)),borderRadius:r+"px",padding:`${p}px ${p*2}px`,fontSize:f+"px"};return `.button {\n  background: ${v._s.background};\n  color: ${v._s.color};\n  border: 0;\n  border-radius: ${v._s.borderRadius};\n  padding: ${v._s.padding};\n  font-size: ${v._s.fontSize};\n  cursor: pointer;\n}`},preview:(v,el)=>pv(el,b=>{const x=h("button");Object.assign(x.style,v._s,{border:"0"});x.textContent=v.t||"Button";b.append(x)})},
"css-minifier":tp(t=>cssMin(t)),"css-formatter":tp(cssFmt),
"html-minifier":tp(t=>{htmlChk(t);return t.replace(/<!--[\s\S]*?-->/g,"").replace(/>\s+</g,"><").replace(/\s{2,}/g," ").trim()}),
"html-formatter":tp(t=>{htmlChk(t);let i=0;const o=[];(t.replace(/<!--[\s\S]*?-->/g,m=>m).match(/<!--[\s\S]*?-->|<[^>]+>|[^<]+/g)||[]).forEach(k=>{k=k.trim();if(!k)return;if(/^<\//.test(k))i=Math.max(0,i-1);o.push("  ".repeat(i)+k);if(/^<[a-z]/i.test(k)&&!VOID.test(k)&&!/\/>$/.test(k)&&!/^<(script|style)/i.test(k)||/^<(script|style)\b[^>]*>$/i.test(k))i++});return o.join("\n")}),
"stopwatch":{mount(r){let t0=0,acc=0,iv=null;const f=ms=>{const s=ms/1e3|0;return[s/3600|0,s/60%60|0,s%60].map(x=>String(x).padStart(2,"0")).join(":")+"."+Math.floor(ms%1e3/100)},d=h("output",{class:"big"},"00:00:00.0"),l=h("ol"),cur=()=>acc+(iv?performance.now()-t0:0),go=h("button",{class:"btn pri",type:"button"},"Start"),tick=()=>{d.textContent=f(cur())};go.onclick=()=>{if(iv){acc=cur();clearInterval(iv);iv=null;go.textContent="Start";tick()}else{t0=performance.now();iv=setInterval(tick,50);go.textContent="Stop"}};r.append(d,h("div",{class:"row"},go,h("button",{class:"btn",type:"button",onclick:()=>{if(cur()>0)l.prepend(h("li",{},f(cur())))}},"Lap"),h("button",{class:"btn",type:"button",onclick:()=>{clearInterval(iv);iv=null;acc=0;go.textContent="Start";l.textContent="";tick()}},"Reset")),l);return()=>clearInterval(iv)}},
"digital-clock":{mount(r){const d=h("output",{class:"big"}),c=h("input",{type:"checkbox"}),z=h("small",{},Intl.DateTimeFormat().resolvedOptions().timeZone),u=()=>{const n=new Date();d.textContent=n.toLocaleTimeString([],{hour12:!c.checked,hour:"2-digit",minute:"2-digit",second:"2-digit"})};u();const iv=setInterval(u,1e3);r.append(d,z,h("label",{class:"chk"},c,"24-hour clock"));c.onchange=u;return()=>clearInterval(iv)}},
"timer":{mount(r){let iv=null,end=0,left=0;const m=h("input",{type:"number",min:0,value:5,id:"tm","aria-label":"Minutes"}),s=h("input",{type:"number",min:0,max:59,value:0,"aria-label":"Seconds"}),d=h("output",{class:"big","aria-live":"off"},"05:00"),f=x=>{x=Math.max(0,Math.ceil(x/1e3));return String(x/60|0).padStart(2,"0")+":"+String(x%60).padStart(2,"0")},go=h("button",{class:"btn pri",type:"button"},"Start"),stop=()=>{clearInterval(iv);iv=null;go.textContent="Start"};go.onclick=()=>{if(iv){left=end-Date.now();stop();return}if(!left){const a=+m.value,b=+s.value;if(!(a>=0&&b>=0)||a+b===0)return JT.toast("Enter a time above zero.","err");left=(a*60+b)*1e3}end=Date.now()+left;go.textContent="Pause";iv=setInterval(()=>{const x=end-Date.now();d.textContent=f(x);if(x<=0){stop();left=0;d.textContent="00:00";JT.toast("Timer finished")}},200)};r.append(h("label",{for:"tm"},"Minutes"),m,h("label",{},"Seconds"),s,d,h("div",{class:"row"},go,h("button",{class:"btn",type:"button",onclick:()=>{stop();left=0;d.textContent=f((+m.value*60+ +s.value)*1e3)}},"Reset")));return stop}},
"countdown-timer":{mount(r){const t=h("input",{type:"datetime-local",id:"cd"}),d=h("output",{class:"big"},"--"),u=()=>{if(!t.value){d.textContent="--";return}const x=new Date(t.value)-Date.now();if(isNaN(x))return;if(x<=0){d.textContent="The target time has passed.";return}const s=x/1e3|0;d.textContent=`${s/86400|0}d ${s/3600%24|0}h ${s/60%60|0}m ${s%60}s`};t.oninput=u;const iv=setInterval(u,1e3);r.append(h("label",{for:"cd"},"Count down to"),t,d);return()=>clearInterval(iv)}},
"keyboard-tester":{mount(r){const o=h("div",{class:"pad",tabindex:"0"},"Click here, then press any key"),lg=h("ol");o.onkeydown=e=>{e.preventDefault();o.textContent="";o.append(h("output",{class:"big"},e.key===" "?"Space":e.key),h("div",{},`code: ${e.code}  |  keyCode: ${e.keyCode}`));lg.prepend(h("li",{},`${e.key===" "?"Space":e.key} (${e.code})`));while(lg.children.length>12)lg.lastChild.remove()};r.append(o,lg)}},
"mouse-tester":{mount(r){const c={0:0,1:0,2:0},o=h("div",{class:"pad"},"Click, right-click or scroll here"),u=(e,w)=>{o.textContent=`Left: ${c[0]}  Middle: ${c[1]}  Right: ${c[2]}\nPosition: ${Math.round(e.offsetX)}, ${Math.round(e.offsetY)}${w?"\nScroll: "+(e.deltaY>0?"down":"up"):""}`;o.style.whiteSpace="pre-line"};o.onmousedown=e=>{c[e.button]=(c[e.button]||0)+1;u(e)};o.onmousemove=e=>u(e);o.oncontextmenu=e=>e.preventDefault();o.onwheel=e=>{e.preventDefault();u(e,1)};r.append(o)}}
});})();
