// Usage: node generator/build.js  -> writes index, categories, tools, search, 404, sitemap, robots
const fs=require("fs"),path=require("path"),R=p=>path.join(__dirname,"..",p),J=p=>JSON.parse(fs.readFileSync(R(p),"utf8"));
const cfg=J("data/config.json"),cats=J("data/categories.json"),tools=J("data/tools.json").filter(t=>t.status==="active");
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
["tools","categories","search","about","privacy","terms","disclaimer","contact","refund-policy"].forEach(d=>fs.rmSync(R(d),{recursive:true,force:true}));
const write=(p,h)=>{fs.mkdirSync(path.dirname(R(p)),{recursive:true});fs.writeFileSync(R(p),h)};
const cat=id=>cats.find(c=>c.id===id);
const ids=new Set();tools.forEach(t=>{if(ids.has(t.id))throw new Error("Duplicate id "+t.id);ids.add(t.id);if(!cat(t.category))throw new Error("Bad category for "+t.id)});
const canon=u=>cfg.siteUrl+u;
const ic={image:'<rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="9" cy="9" r="2"/><path d="m21 15-5-5L5 21"/>',pdf:'<path d="M14 3H7a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V8z"/><path d="M14 3v5h5M9 13h6M9 17h4"/>',text:'<path d="M4 7V5h16v2M9 19h6M12 5v14"/>',calc:'<rect x="5" y="3" width="14" height="18" rx="2"/><path d="M8 7h8M8 12h.01M12 12h.01M16 12h.01M8 16h.01M12 16h.01M16 16h.01"/>',convert:'<path d="M7 4 3 8l4 4M3 8h14M17 20l4-4-4-4M21 16H7"/>',lock:'<rect x="4" y="11" width="16" height="10" rx="2"/><path d="M8 11V7a4 4 0 0 1 8 0v4"/>',code:'<path d="m8 8-5 4 5 4M16 8l5 4-5 4M14 5l-4 14"/>',palette:'<path d="M12 3a9 9 0 1 0 0 18c1.2 0 2-.8 2-1.8 0-1-.7-1.5-.7-2.4 0-.9.7-1.6 1.7-1.6H17a4 4 0 0 0 4-4c0-4.4-4-8.2-9-8.2z"/><circle cx="7.5" cy="11" r="1"/><circle cx="12" cy="7.5" r="1"/><circle cx="16.5" cy="10" r="1"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',brief:'<rect x="3" y="7" width="18" height="13" rx="2"/><path d="M9 7V5a2 2 0 0 1 2-2h2a2 2 0 0 1 2 2v2M3 13h18"/>',bolt:'<path d="M13 2 4 14h7l-1 8 9-12h-7z"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',heart:'<path d="M12 21s-8-5-8-11a4.5 4.5 0 0 1 8-2.8A4.5 4.5 0 0 1 20 10c0 6-8 11-8 11z"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/>',arrow:'<path d="M5 12h14M13 6l6 6-6 6"/>',shield:'<path d="M12 3 4 6v6c0 5 3.5 8 8 9 4.5-1 8-4 8-9V6z"/><path d="m9 12 2 2 4-4"/>',gift:'<rect x="3" y="8" width="18" height="4" rx="1"/><path d="M12 8v13M5 12v9h14v-9M12 8a3 3 0 1 0-3-3c0 1.7 3 3 3 3zm0 0a3 3 0 1 1 3-3c0 1.7-3 3-3 3z"/>',wand:'<path d="m4 20 11-11M14 4l1 2 2 1-2 1-1 2-1-2-2-1 2-1zM19 12l.7 1.3L21 14l-1.3.7L19 16l-.7-1.3L17 14l1.3-.7z"/>'};
const svg=n=>`<svg class="ic" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${ic[n]}</svg>`;
const CI={"image-tools":"image","pdf-tools":"pdf","text-tools":"text","calculators":"calc","converters":"convert","security-tools":"lock","developer-tools":"code","design-tools":"palette","utilities":"clock","business-tools":"brief"};
const usedCats=cats.filter(c=>tools.some(t=>t.category===c.id));
function layout({root,url,title,desc,body,extraLd=[],scripts=""}){
const ld=JSON.stringify(extraLd.length?extraLd:[{"@context":"https://schema.org","@type":"WebSite",name:cfg.siteName,url:cfg.siteUrl}]).replace(/</g,"\\u003c");
return `<!doctype html><html lang="en" data-root="${root}" data-theme="${cfg.defaultTheme}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${esc(title)}</title><meta name="description" content="${esc(desc)}"><link rel="canonical" href="${canon(url)}"><meta name="robots" content="index,follow"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(desc)}"><meta property="og:url" content="${canon(url)}"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${esc(title)}"><meta name="twitter:description" content="${esc(desc)}"><link rel="manifest" href="${root}manifest.json"><meta name="theme-color" content="#050812"><link rel="icon" href="${root}assets/icons/icon.svg" type="image/svg+xml"><link rel="stylesheet" href="${root}css/style.css"><script type="application/ld+json">${ld}</script></head><body><a class="skip" href="#main">Skip to content</a>
<header class="top"><a class="logo" href="${root}">${svg("bolt")}<span>JADON TOOLS</span></a><nav id="menu" aria-label="Main"><a href="${root}">Home</a><a href="${root}#categories">Categories</a><a href="${root}#popular">Popular</a><a href="${root}#all">All Tools</a><a class="m" href="${root}#favorites">Favorites</a><a class="m" href="${root}#recent">Recently Used</a><a class="m" href="${root}about/">About</a><a class="m" href="${root}contact/">Contact</a><a class="m" href="${root}privacy/">Privacy Policy</a><a class="m" href="${root}terms/">Terms &amp; Conditions</a></nav><div class="acts"><a class="btn icon" href="${root}search/" aria-label="Search tools">${svg("search")}</a><a class="btn icon" href="${root}#favorites" aria-label="Favorites">${svg("heart")}</a><button class="btn icon" data-theme-toggle aria-label="Switch theme">${svg("sun")}</button></div><button class="btn icon menu-btn" id="menu-btn" aria-expanded="false" aria-controls="menu" aria-label="Open menu">${svg("menu")}</button></header>
<main id="main">${body}</main><footer><div class="fgrid"><div><a class="logo" href="${root}">${svg("bolt")}<span>JADON TOOLS</span></a><p>Fast, simple online tools for everyday work. Everything You Need. One Powerful Toolkit.</p></div><div><h3>Tools</h3><a href="${root}#all">All Tools</a><a href="${root}#popular">Popular</a><a href="${root}#categories">Categories</a></div><div><h3>Company</h3><a href="${root}about/">About</a><a href="${root}contact/">Contact</a><a href="${root}sitemap.xml">Sitemap</a></div><div><h3>Legal</h3><a href="${root}privacy/">Privacy Policy</a><a href="${root}terms/">Terms &amp; Conditions</a><a href="${root}refund-policy/">Refund Policy</a><a href="${root}disclaimer/">Disclaimer</a></div></div><p class="fcopy">© ${new Date().getFullYear()} Jadon Tools. Results are informational; verify important calculations independently.</p></footer>${scripts}</body></html>`}
const card=(t,root)=>`<article class="card" data-id="${t.id}" data-cat="${t.category}" data-s="${esc((t.name+" "+t.description+" "+t.keywords.join(" ")+" "+cat(t.category).name).toLowerCase())}"><span class="tile">${svg(CI[t.category])}</span><button class="fav" data-fav="${t.id}" aria-label="Favorite ${esc(t.name)}" aria-pressed="false">☆</button><a class="open" href="${root}tools/${t.id}/">${esc(t.name)}</a><p>${esc(t.description)}</p><small>${esc(cat(t.category).name)} ${svg("arrow")}</small></article>`;
const grid=(l,root,id="")=>`<div class="grid"${id?` id="${id}"`:""}>${l.map(t=>card(t,root)).join("")}</div>`;
const core=root=>`<script src="${root}js/core.js" defer></script>`;
// Home
const why=[["clock","Fast","Tools load instantly and run right in your browser."],["shield","Private","Most tools process your input locally on your device."],["gift","Free","No login, no subscription for everyday tools."],["wand","Simple","Clean tools that do one job well."]];
write("index.html",layout({root:"./",url:"",title:"Jadon Tools: Everything You Need. One Powerful Toolkit.",desc:"Fast, simple online tools for images, PDFs, text, calculations, conversions, developers and everyday work.",scripts:core("./"),
body:`<section class="hero"><span class="pill">${svg("bolt")} ${tools.length} free tools</span><p class="brand">JADON TOOLS</p><h1>Everything You Need.<br>One Powerful Toolkit.</h1><p class="sub">Fast, simple online tools for images, PDFs, text, calculations, conversions, developers and everyday work.</p><div class="row"><a class="btn pri" href="#all">Explore All Tools ${svg("arrow")}</a><a class="btn" href="#popular">Popular Tools</a></div>
<div class="search">${svg("search")}<label class="sr" for="q" style="position:absolute;left:-999px">Search tools</label><input id="q" type="search" placeholder="Search ${tools.length} tools..." autocomplete="off"><kbd>Ctrl K</kbd></div>
<div class="chips" id="chips" role="group" aria-label="Filter by category"><button class="chip on" data-cat="">All</button>${usedCats.map(c=>`<button class="chip" data-cat="${c.id}" data-c="${c.id}">${svg(CI[c.id])}${esc(c.name.replace(/ Tools$/,""))}</button>`).join("")}</div><p>Your input is processed locally in your browser whenever a tool allows it.</p></section>
<p id="empty" class="empty" hidden>No tools found. Try a different word.</p>
<h2 id="popular">Popular Tools</h2>${grid(tools.filter(t=>t.popular),"./")}
<section id="recent" hidden><h2>Recently Used</h2><div class="grid" id="recent-list"></div></section>
<section id="favorites"><h2>Favorites</h2><div class="grid" id="fav-list"></div><div class="empty" id="fav-empty"><h3>No Favorite Tools Yet</h3><p>Save tools here for quick access.</p><a class="btn pri" href="#all">Explore Tools</a></div></section>
<h2 id="all">All Tools (${tools.length})</h2>${grid([...tools].sort((a,b)=>a.name.localeCompare(b.name)),"./","all-grid")}
<h2 id="categories">Explore by category</h2><div class="grid">${usedCats.map(c=>`<article class="card" data-cat="${c.id}"><span class="tile">${svg(CI[c.id])}</span><a class="open" href="./categories/${c.id}/">${esc(c.name)}</a><p>${esc(c.description)}</p><small>${tools.filter(t=>t.category===c.id).length} tools ${svg("arrow")}</small></article>`).join("")}</div>
<h2>Why Jadon Tools?</h2><div class="why">${why.map(([i,h,d],n)=>`<div class="card" data-cat="${["image-tools","converters","security-tools","utilities"][n]}"><span class="tile">${svg(i)}</span><h3>${h}</h3><p style="display:block">${d}</p></div>`).join("")}</div>`}));
// Search
write("search/index.html",layout({root:"../",url:"search/",title:"Search Tools | Jadon Tools",desc:"Search all Jadon Tools by name, keyword or category.",scripts:core("../"),body:`<h1>Search tools</h1><label for="q">Search</label><input id="q" type="search" placeholder="Try: image, json, password"><p id="empty" hidden>No tools found. Try a different word.</p>${grid(tools,"../")}`}));
// Categories
cats.forEach(c=>{const l=tools.filter(t=>t.category===c.id);if(!l.length)return;const u=`categories/${c.id}/`;
write(u+"index.html",layout({root:"../../",url:u,title:`${c.name} | Free Online Tools | Jadon Tools`,desc:`${c.description} ${l.length} free tools.`,scripts:core("../../"),extraLd:[{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:cfg.siteUrl},{"@type":"ListItem",position:2,name:c.name,item:canon(u)}]}],body:`<p class="crumbs"><a href="../../">Home</a> / ${esc(c.name)}</p><h1>${esc(c.name)}</h1><p>${esc(c.description)} (${l.length} tools)</p>${grid(l,"../../")}`}))});
// Tool pages
tools.forEach(t=>{const c=cat(t.category),u=`tools/${t.id}/`,rel=tools.filter(x=>x.id!==t.id).map(x=>({x,s:(x.category===t.category?3:0)+x.keywords.filter(k=>t.keywords.includes(k)).length})).sort((a,b)=>b.s-a.s).slice(0,3).map(o=>o.x);
const faq=t.faq||[{q:`Is ${t.name} free?`,a:"Yes. It is free and needs no login."},{q:"Is my input uploaded?",a:"No. This tool runs in your browser and does not send your input to a server."}];
const meta={adAfterUse:t.adAfterUse,adCooldownMs:t.adCooldownMs,cat:t.category};
write(u+"index.html",layout({root:"../../",url:u,title:`${t.name} | Free Online ${c.name.replace(/ Tools$/,"")} Tool | Jadon Tools`,desc:t.description,scripts:`<script src="../../js/tools.js" defer></script>${t.module?`<script src="../../js/tools-${t.module}.js" defer></script>`:""}${core("../../")}<script src="../../js/magic.js" defer></script>`,
extraLd:[{"@context":"https://schema.org","@type":"WebApplication",name:t.name,url:canon(u),description:t.description,applicationCategory:"UtilitiesApplication",operatingSystem:"Any",offers:{"@type":"Offer",price:"0",priceCurrency:"USD"}},{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:cfg.siteUrl},{"@type":"ListItem",position:2,name:c.name,item:canon(`categories/${c.id}/`)},{"@type":"ListItem",position:3,name:t.name,item:canon(u)}]},{"@context":"https://schema.org","@type":"FAQPage",mainEntity:faq.map(f=>({"@type":"Question",name:f.q,acceptedAnswer:{"@type":"Answer",text:f.a}}))}],
body:`<p class="crumbs"><a href="../../">Home</a> / <a href="../../categories/${c.id}/">${esc(c.name)}</a> / ${esc(t.name)}</p><div class="thead"><span class="tile lg" data-cat="${t.category}">${svg(CI[t.category])}</span><div><h1>${esc(t.name)}</h1><p>${esc(t.description)}</p></div><button class="fav" data-fav="${t.id}" aria-label="Favorite ${esc(t.name)}" aria-pressed="false">☆</button></div><p><a class="btn" href="../../categories/${c.id}/">← Back</a></p><p><span class="badge">Local</span>${(t.permissions||[]).map(p=>`<span class="badge">${p} permission</span>`).join("")}${t.offline?'<span class="badge">Works offline once loaded</span>':""}</p><p>${t.lib?"Files are processed locally in your browser. A small helper library may be loaded from a public CDN (jsDelivr, unpkg or cdnjs) when you use this tool.":"Processed locally in your browser."}</p>
<div class="ad" hidden id="ad-post-action" role="complementary" aria-label="Advertisement"></div>
<section class="panel" id="tool" data-id="${t.id}" data-meta='${esc(JSON.stringify(meta))}'><form id="form" onsubmit="return false"></form><div class="row"><button class="btn pri" id="run" type="button">Run</button><button class="btn" id="reset" type="button">Reset</button></div><p class="err" id="err" role="alert" hidden></p><div id="files" class="row"></div><div id="preview" class="preview" hidden></div><label for="out">Result</label><textarea id="out" rows="6" readonly></textarea><div class="row" id="acts" hidden><button class="btn" id="copy" type="button">Copy</button><button class="btn" id="dl" type="button">Download</button><button class="btn" id="share" type="button">Share</button></div></section>
<h2>Features</h2><ul><li>Runs in your browser with no login</li><li>Copy or download the result</li><li>Works on mobile and desktop</li></ul><h2>How to use</h2><p>Enter your values above, press Run, then copy or download the result. Use Reset to start again.</p><h2>FAQ</h2>${faq.map(f=>`<details><summary>${esc(f.q)}</summary><p>${esc(f.a)}</p></details>`).join("")}<h2>Related tools</h2>${grid(rel,"../../")}`}))});

const LEGAL={
about:["About Jadon Tools","<p>Jadon Tools is a collection of free browser-based tools for everyday tasks such as text, calculations, unit conversion and developer helpers. Each tool has its own page and works without an account.</p>"],
privacy:["Privacy Policy","<p>Tools on this site run in your browser. The text and numbers you enter are not sent to our server by the tools.</p><h2>What is stored on your device</h2><p>Your browser localStorage keeps your theme choice, favorite tools, recently opened tool IDs and advertising frequency counters. Clear it any time from your browser settings.</p><h2>Advertising and analytics</h2><p>Advertising runs in test mode and analytics is switched off by default. If a live ad provider or analytics service is enabled later, this page will be updated to name it and explain what it collects.</p><h2>Hosting</h2><p>The site is hosted on GitHub Pages, which may log standard request data such as IP addresses under its own policy.</p>"],
terms:["Terms of Use","<p>By using Jadon Tools you agree to use it lawfully and at your own responsibility.</p><h2>Acceptable use</h2><p>Do not misuse the site, attempt to disrupt it or use it to harm others.</p><h2>Availability and changes</h2><p>Tools are provided as is, may change or become unavailable, and may rely on third-party services such as GitHub Pages.</p><h2>Liability</h2><p>Results may contain errors. You are responsible for checking anything important before relying on it.</p>"],
disclaimer:["Disclaimer","<p>Results from calculators and converters are informational only and are not financial, legal, tax, accounting or medical advice. Verify important figures independently. Loan, interest and similar results may differ from the terms of a real lender or institution.</p><p>Generated passwords use your browser's secure random generator, but you are responsible for storing them safely.</p>"],
"refund-policy":["Refund Policy","<p>Jadon Tools is free to use and does not sell paid products or subscriptions, so there is nothing to refund. If paid features are ever added, this page will describe the refund terms before any payment is taken.</p>"],
contact:["Contact","<p>To report a bug or suggest a tool, open an issue on the project's GitHub repository: <a href=\"https://github.com/asjadonsolutions/JadonTools/issues\" rel=\"noopener\">github.com/asjadonsolutions/JadonTools</a>.</p>"]};
Object.entries(LEGAL).forEach(([k,[h,b]])=>write(k+"/index.html",layout({root:"../",url:k+"/",title:h+" | Jadon Tools",desc:h+" for Jadon Tools, a set of free online tools.",scripts:core("../"),body:`<h1>${h}</h1>${b}`})));
// 404, sitemap, robots
write("404.html",layout({root:"/JadonTools/",url:"404.html",title:"Page not found | Jadon Tools",desc:"This page does not exist.",scripts:core("/JadonTools/"),body:`<h1>Page not found</h1><p>That page does not exist. Search for a tool or go home.</p><p><a class="btn pri" href="/JadonTools/">Home</a> <button class="btn" onclick="history.back()">Go back</button></p><label for="q">Search tools</label><input id="q" type="search"><p id="empty" hidden>No tools found.</p>${grid(tools.filter(t=>t.popular),"/JadonTools/")}`}));
const urls=["",...cats.filter(c=>tools.some(t=>t.category===c.id)).map(c=>`categories/${c.id}/`),"search/",...Object.keys(LEGAL).map(k=>k+"/"),...tools.map(t=>`tools/${t.id}/`)];
write("sitemap.xml",`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(u=>`<url><loc>${canon(u)}</loc></url>`).join("\n")}\n</urlset>\n`);
write("robots.txt",`User-agent: *\nAllow: /\nSitemap: ${cfg.siteUrl}sitemap.xml\n`);
const V="JADON_TOOLS_CACHE_V"+cfg.version;
const pre=["./","404.html","css/style.css","js/core.js","js/magic.js","js/tools.js","data/config.json","manifest.json","assets/icons/icon.svg",...urls.filter(u=>u)];
write("sw.js",`const C="${V}",A=${JSON.stringify(pre)};
self.addEventListener("install",e=>{e.waitUntil(caches.open(C).then(c=>c.addAll(A)).then(()=>self.skipWaiting()))});
self.addEventListener("activate",e=>{e.waitUntil(caches.keys().then(k=>Promise.all(k.filter(x=>x.startsWith("JADON_TOOLS_CACHE")&&x!==C).map(x=>caches.delete(x)))).then(()=>self.clients.claim()))});
self.addEventListener("fetch",e=>{if(e.request.method!=="GET"||new URL(e.request.url).origin!==location.origin)return;
e.respondWith(fetch(e.request).then(r=>{if(r.ok){const c=r.clone();caches.open(C).then(x=>x.put(e.request,c))}return r}).catch(()=>caches.match(e.request).then(r=>r||caches.match("404.html"))))});
`);
console.log("Built",tools.length,"tools,",urls.length,"URLs");
