'use strict';
const $=(s,r=document)=>r.querySelector(s),AD='<div class="ad-slot"></div>';
const fmt=x=>Number(x).toLocaleString('en-IN',{maximumFractionDigits:2});
const bad=m=>Object.assign(Error(m),{u:1});
const num=v=>{if(v==null||String(v).trim()==='')throw bad('Please enter a value.');const x=Number(v);if(!isFinite(x))throw bad('Please enter a valid number.');return x};
const chk=(v,l,z)=>{const x=num(v);if(z?x<0:x<=0)throw bad(l+(z?' cannot be negative.':' must be greater than 0.'));return x};
const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const rows=a=>'<dl class="res">'+a.map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('')+'</dl>';
const day=s=>{const d=new Date(s+'T00:00');if(!s||isNaN(d))throw bad('Please select a valid date.');return d};
const emi=(P,r,n)=>{const m=r/1200,e=m?P*m*(1+m)**n/((1+m)**n-1):P/n;return rows([['Monthly EMI',fmt(e)],['Total interest',fmt(e*n-P)],['Total payment',fmt(e*n)]])};
const U={Length:{m:1,km:1e3,cm:.01,mm:.001,mi:1609.344,ft:.3048,in:.0254},Weight:{kg:1,g:.001,lb:.45359237,oz:.028349523},'Data size':{B:1,KB:1024,MB:1048576,GB:1073741824,TB:1099511627776},Temperature:{'°C':1,'°F':1,K:1}};
const loadLib=(u,g)=>new Promise((ok,no)=>{if(window[g])return ok();const s=document.createElement('script');s.src=u;s.onload=ok;s.onerror=()=>no(bad('Could not load the required library. Check your connection.'));document.head.append(s)});
const wc=t=>[['Words',(t.trim().match(/\S+/g)||[]).length],['Characters',t.length],['Characters without spaces',t.replace(/\s/g,'').length],['Sentences',(t.match(/[^.!?]+[.!?]+|[^.!?]+$/g)||[]).filter(s=>s.trim()).length],['Paragraphs',t.split(/\n\s*\n/).filter(s=>s.trim()).length]];
const T=[
{id:'age',n:'Age Calculator',c:['Calculators','Students'],i:'🎂',d:'Find your exact age in years, months and days.',k:'birthday dob',f:[['dob','Date of birth','date']],run:v=>{const b=day(v.dob),n=new Date();if(b>n)throw bad('Date of birth cannot be in the future.');let y=n.getFullYear()-b.getFullYear(),m=n.getMonth()-b.getMonth(),d=n.getDate()-b.getDate();if(d<0){m--;d+=new Date(n.getFullYear(),n.getMonth(),0).getDate()}if(m<0){y--;m+=12}return rows([['Age',`${y} years, ${m} months, ${d} days`],['Total days lived',fmt(Math.floor((n-b)/864e5))]])}},
{id:'pct',n:'Percentage Calculator',c:['Calculators','Students'],i:'％',d:'Work out percentages and “what is X% of Y”.',k:'percent',f:[['a','Value'],['b','Total'],['p','X (%) for “X% of Y”'],['y','Y']],run:v=>{const A=v.a!==''||v.b!=='',B=v.p!==''||v.y!=='';if(!A&&!B)throw bad('Please enter a value.');const o=[];if(A){const x=num(v.a),t=num(v.b);if(!t)throw bad('Total cannot be zero.');o.push([`${fmt(x)} is what % of ${fmt(t)}`,fmt(x/t*100)+'%'])}if(B){const p=num(v.p),y=num(v.y);o.push([`${fmt(p)}% of ${fmt(y)}`,fmt(p*y/100)])}return rows(o)}},
{id:'gst',n:'GST Calculator',c:['Calculators'],i:'🧾',d:'Add or remove GST from any amount.',k:'gst tax vat',f:[['a','Amount'],['r','GST %'],['m','Mode','select',['Add GST','Remove GST']]],run:v=>{const a=chk(v.a,'Amount'),r=chk(v.r,'GST %',1),add=v.m==='Add GST',base=add?a:a/(1+r/100),g=base*r/100;return rows([['Original amount',fmt(a)],['GST amount',fmt(g)],[add?'Final amount (with GST)':'Amount without GST',fmt(base+(add?g:0))]])}},
{id:'emi',n:'EMI Calculator',c:['Calculators'],i:'🏦',d:'Calculate monthly EMI, total interest and payment.',k:'loan',f:[['p','Loan amount'],['r','Interest rate (% per year)'],['n','Duration (months)']],run:v=>emi(chk(v.p,'Loan amount'),chk(v.r,'Interest rate',1),Math.round(chk(v.n,'Duration')))},
{id:'sal',n:'Salary Calculator',c:['Calculators'],i:'💼',d:'Convert monthly salary to annual and daily estimates.',k:'income pay',f:[['s','Monthly salary']],run:v=>{const s=chk(v.s,'Salary');return rows([['Monthly salary',fmt(s)],['Annual salary',fmt(s*12)],['Estimated daily salary',fmt(s*12/365)]])+'<p class=note>Estimates only (annual ÷ 365). Tax and deductions are not included.</p>'}},
{id:'loan',n:'Loan Calculator',c:['Calculators'],i:'💰',d:'Find EMI, total interest and total repayment.',k:'repayment principal',f:[['p','Principal'],['r','Interest (% per year)'],['y','Duration (years)']],run:v=>emi(chk(v.p,'Principal'),chk(v.r,'Interest',1),Math.round(chk(v.y,'Duration')*12))},
{id:'disc',n:'Discount Calculator',c:['Calculators'],i:'🏷️',d:'See the discount amount and final price.',k:'sale offer',f:[['p','Original price'],['d','Discount %']],run:v=>{const p=chk(v.p,'Price'),d=chk(v.d,'Discount',1);if(d>100)throw bad('Discount cannot be more than 100%.');return rows([['Discount amount',fmt(p*d/100)],['Final price',fmt(p-p*d/100)]])}},
{id:'bmi',n:'BMI Calculator',c:['Calculators'],i:'⚖️',d:'Check your body mass index from height and weight.',k:'health weight',f:[['h','Height (cm)'],['w','Weight (kg)']],run:v=>{const h=chk(v.h,'Height'),w=chk(v.w,'Weight'),b=w/(h/100)**2;return rows([['BMI',b.toFixed(1)],['Category',b<18.5?'Underweight':b<25?'Normal':b<30?'Overweight':'Obese']])+'<p class=note>BMI is only a basic screening measure, not a medical diagnosis.</p>'}},
{id:'words',n:'Word Counter',c:['Text','Students'],i:'📝',d:'Count words, characters, sentences and paragraphs live.',k:'text count',live:1,f:[['t','Your text','textarea']],run:v=>rows(wc(v.t))},
{id:'chars',n:'Character Counter',c:['Text','Students'],i:'🔤',d:'Count characters as you type.',k:'text length',live:1,f:[['t','Your text','textarea']],run:v=>rows(wc(v.t).slice(1,3))},
{id:'unit',n:'Unit Converter',c:['Calculators','Students'],i:'📏',d:'Convert length, weight, temperature and data size.',k:'convert',f:[['ty','Type','select',Object.keys(U)],['v','Value'],['f','From','select',[]],['t','To','select',[]]],init:f=>{const fill=()=>{f.f.innerHTML=Object.keys(U[f.ty.value]).map(o=>`<option>${o}</option>`).join('');f.t.innerHTML=f.f.innerHTML;f.t.selectedIndex=1};f.ty.onchange=fill;fill()},run:v=>{const x=num(v.v);let r;if(v.ty==='Temperature'){const c=v.f==='°C'?x:v.f==='°F'?(x-32)*5/9:x-273.15;r=v.t==='°C'?c:v.t==='°F'?c*9/5+32:c+273.15}else r=x*U[v.ty][v.f]/U[v.ty][v.t];return rows([[`${fmt(x)} ${v.f}`,`${+r.toPrecision(8)} ${v.t}`]])}},
{id:'date',n:'Date Calculator',c:['Calculators','Students'],i:'📅',d:'Find the gap between dates or add/subtract days.',k:'days difference',f:[['m','Action','select',['Difference between dates','Add days','Subtract days']],['a','Start date','date'],['b','End date (for difference)','date'],['d','Days (for add/subtract)']],run:v=>{const a=day(v.a);if(v.m[0]==='D'){const n=Math.round((day(v.b)-a)/864e5);return rows([['Difference',Math.abs(n)+' days'],['Weeks',fmt(Math.abs(n)/7)]])}const n=Math.round(chk(v.d,'Days',1));a.setDate(a.getDate()+(v.m[0]==='A'?n:-n));return rows([['Result',a.toDateString()]])}},
{id:'qr',n:'QR Code Generator',c:['QR'],i:'▦',d:'Create a QR code from text or a link and download it.',k:'qr link url',custom:qrTool},
{id:'imgc',n:'Image Compressor',c:['Images'],i:'🗜️',d:'Reduce image file size right in your browser.',k:'image compress photo',custom:b=>imgTool(b,'c')},
{id:'imgr',n:'Image Resizer',c:['Images'],i:'↔️',d:'Resize images by width and height.',k:'image resize photo',custom:b=>imgTool(b,'r')},
{id:'pdf',n:'JPG/PNG to PDF',c:['PDF','Images'],i:'📄',d:'Turn a JPG or PNG picture into a PDF file.',k:'image jpg png pdf convert',custom:b=>imgTool(b,'p')},
{id:'resume',n:'Resume Maker',c:['Jobs'],i:'📋',d:'Build a clean resume and save it as PDF.',k:'resume cv job',live:1,act:['print'],f:[['name','Full name','text'],['phone','Phone','text'],['email','Email','text'],['loc','Location','text'],['qual','Qualification','text'],['inst','Institute','text'],['yr','Year','text'],['co','Company','text'],['job','Job title','text'],['dur','Duration','text'],['sk','Skills (comma separated)','text'],['sum','Professional summary','textarea']],run:v=>{if(!v.name.trim())return'<p class=mut>Enter your name to see the resume preview.</p>';const e=esc,s=(h,x)=>x?`<h3>${h}</h3>${x}`:'';return`<div class=doc><h1>${e(v.name)}</h1><p>${[v.phone,v.email,v.loc].filter(Boolean).map(e).join(' • ')}</p>${s('Summary',v.sum&&`<p>${e(v.sum)}</p>`)}${s('Experience',(v.co||v.job)&&`<p><b>${e(v.job)}</b> — ${e(v.co)} <i>${e(v.dur)}</i></p>`)}${s('Education',(v.qual||v.inst)&&`<p><b>${e(v.qual)}</b> — ${e(v.inst)} ${e(v.yr)}</p>`)}${s('Skills',v.sk&&`<p>${v.sk.split(',').map(x=>e(x.trim())).filter(Boolean).join(' • ')}</p>`)}</div>`}},
{id:'cover',n:'Cover Letter Maker',c:['Jobs'],i:'✉️',d:'Generate an editable cover letter you can copy or print.',k:'resume job letter',live:1,act:['copy','print'],f:[['name','Your name','text'],['job','Job title','text'],['co','Company','text'],['sk','Key skills','text'],['exp','Experience (e.g. 3 years in sales)','text']],run:v=>{if(!v.name.trim()||!v.job.trim()||!v.co.trim())return'<p class=mut>Enter name, job title and company to generate the letter.</p>';const e=esc;return`<div class="doc" contenteditable="true"><p>Dear Hiring Manager,</p><p>I am writing to apply for the ${e(v.job)} position at ${e(v.co)}.${v.exp?` I bring ${e(v.exp)}.`:''}${v.sk?` My key strengths include ${e(v.sk)}.`:''}</p><p>I am motivated, reliable and eager to contribute to ${e(v.co)}. I would welcome the chance to discuss how I can support your team.</p><p>Thank you for your time and consideration.</p><p>Sincerely,<br>${e(v.name)}</p></div>`}}
];
const CATS=['All','Calculators','PDF','Images','Jobs','QR','Text','Students','AI'];let cat='All';
const grid=$('#grid'),dlg=$('#dlg');
function render(){const q=$('#q').value.trim().toLowerCase(),r=T.filter(t=>(cat==='All'||t.c.includes(cat))&&(!q||(t.n+' '+t.d+' '+t.k+' '+t.c.join(' ')).toLowerCase().includes(q)));
grid.innerHTML=r.map(t=>`<article class="card"><span class="ico" aria-hidden="true">${t.i}</span><h3>${t.n}</h3><p class="mut">${t.d}</p><span class="tag">${t.c[0]}</span><button class="btn pri" data-id="${t.id}">Use Tool →</button></article>`).join('');
$('#none').hidden=!!r.length;$('#count').textContent=r.length+' tool'+(r.length==1?'':'s');
$('#chips').innerHTML=CATS.map(c=>`<button class="chip" aria-pressed="${c===cat}" data-c="${c}">${c}</button>`).join('')}
$('#chips').onclick=e=>{const c=e.target.dataset.c;if(c){cat=c;$('#q').value='';render()}};
$('#q').oninput=()=>{cat='All';render()};
$('#q').onkeydown=e=>{if(e.key==='Enter')$('#tools').scrollIntoView()};
$('#sbtn').onclick=()=>{$('#top').scrollIntoView();$('#q').focus()};
grid.onclick=e=>{const b=e.target.closest('[data-id]');if(b)openTool(b.dataset.id)};
const fld=([id,l,t='number',o])=>`<label>${l}${t==='select'?`<select name="${id}">${o.map(x=>`<option>${x}</option>`).join('')}</select>`:t==='textarea'?`<textarea name="${id}" rows="7"></textarea>`:`<input name="${id}" type="${t==='number'?'text':t}" ${t==='number'?'inputmode="decimal"':''} autocomplete="off">`}</label>`;
const errHTML=e=>`<p class="err" role="alert">${esc(e.u?e.message:'Something went wrong. Please check your input.')}</p>`;
function makeForm(t,box){
box.innerHTML=`<form novalidate>${t.f.map(fld).join('')}<div class="btns">${t.live?'':'<button class="btn pri">Calculate</button>'}<button type="reset" class="btn">Reset</button>${(t.act||[]).map(a=>`<button type="button" class="btn" data-a="${a}">${a==='print'?'Print / Save as PDF':'Copy'}</button>`).join('')}</div></form><div class="out" aria-live="polite"></div>${AD}`;
const f=$('form',box),out=$('.out',box),v=()=>Object.fromEntries(new FormData(f));
const go=()=>{try{out.innerHTML=t.run(v())}catch(e){out.innerHTML=errHTML(e)}};
t.init&&t.init(f.elements);f.onsubmit=e=>{e.preventDefault();go()};
if(t.live){f.oninput=go;go()}
f.onreset=()=>setTimeout(()=>{out.innerHTML='';t.init&&t.init(f.elements);t.live&&go()});
box.onclick=e=>{const a=e.target.dataset.a,d=$('.doc',out);if(!a)return;if(!d)return alert('Please fill in the form first.');
if(a==='print')printHTML(d.outerHTML);else navigator.clipboard.writeText(d.innerText).then(()=>alert('Copied to clipboard.'),()=>alert('Copy failed. Select the text and copy manually.'))}}
function printHTML(h){$('#pr').innerHTML=h;window.print()}
function qrTool(box){box.innerHTML=`<form novalidate><label>Text or URL<input name="t" autocomplete="off"></label><div class="btns"><button class="btn pri">Generate QR</button><button type="reset" class="btn">Reset</button></div></form><div class="out"></div>${AD}`;
const f=$('form',box),out=$('.out',box);f.onreset=()=>out.innerHTML='';
f.onsubmit=async e=>{e.preventDefault();try{const t=f.t.value.trim();if(!t)throw bad('Please enter a value.');await loadLib('https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js','QRCode');out.innerHTML='<div class="qr"></div><div class="btns"><button type="button" class="btn pri">Download PNG</button></div>';new QRCode($('.qr',out),{text:t,width:256,height:256});$('button',out).onclick=()=>{const a=document.createElement('a');a.href=$('canvas',out).toDataURL('image/png');a.download='qr-code.png';a.click()}}catch(x){out.innerHTML=errHTML(x)}}}
function imgTool(box,m){
box.innerHTML=`<p class="note">🔒 Your image is processed in your browser.</p><form novalidate><label>Select image (JPG, PNG, WebP)<input type="file" name="file" accept="image/*"></label>${m==='c'?'<label>Quality: <b id="qv">70</b>%<input type="range" name="q" min="10" max="95" value="70"></label>':''}${m==='r'?'<div class="two"><label>Width (px)<input name="w" inputmode="numeric"></label><label>Height (px)<input name="h" inputmode="numeric"></label></div><label><input type="checkbox" name="ar" checked>Maintain aspect ratio</label>':''}<div class="btns"><button class="btn pri">${{c:'Compress',r:'Resize',p:'Create PDF'}[m]}</button><button type="reset" class="btn">Reset</button></div></form><div class="out" aria-live="polite"></div>${AD}`;
const f=$('form',box),out=$('.out',box);let img=null,file=null,ratio=1;
f.onreset=()=>{img=file=null;out.innerHTML=''};
if(m==='c')f.q.oninput=()=>$('#qv').textContent=f.q.value;
if(m==='r'){f.w.oninput=()=>{if(f.ar.checked&&+f.w.value>0)f.h.value=Math.round(f.w.value/ratio)};f.h.oninput=()=>{if(f.ar.checked&&+f.h.value>0)f.w.value=Math.round(f.h.value*ratio)}}
f.file.onchange=()=>{file=f.file.files[0];img=null;if(!file)return;if(!file.type.startsWith('image/')){out.innerHTML=errHTML(bad('Please select a valid image file.'));file=null;return}
const u=URL.createObjectURL(file),i=new Image();i.onload=()=>{img=i;ratio=i.naturalWidth/i.naturalHeight;if(m==='r'){f.w.value=i.naturalWidth;f.h.value=i.naturalHeight}out.innerHTML=`<img class="prev" src="${u}" alt="Selected image preview"><p class="note">${i.naturalWidth}×${i.naturalHeight}px, ${(file.size/1024).toFixed(1)} KB</p>`};i.onerror=()=>out.innerHTML=errHTML(bad('This image could not be read.'));i.src=u};
f.onsubmit=async e=>{e.preventDefault();try{if(!img)throw bad('Please select an image.');let w=img.naturalWidth,h=img.naturalHeight;
if(m==='r'){w=Math.round(+f.w.value);h=Math.round(+f.h.value);if(!(w>0&&h>0&&w<=10000&&h<=10000))throw bad('Please enter a valid number.')}
const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d'),png=m==='r'&&file.type==='image/png';if(!png){x.fillStyle='#fff';x.fillRect(0,0,w,h)}x.drawImage(img,0,0,w,h);
const base=file.name.replace(/\.[^.]+$/,'');
if(m==='p'){await loadLib('https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js','jspdf');const d=new window.jspdf.jsPDF({orientation:w>h?'l':'p',unit:'px',format:[w,h]});d.addImage(c.toDataURL('image/jpeg',.92),'JPEG',0,0,w,h);d.save(base+'.pdf');out.innerHTML='<p>PDF created and downloaded.</p>';return}
c.toBlob(b=>{const u=URL.createObjectURL(b),ext=png?'png':'jpg';out.innerHTML=`<img class="prev" src="${u}" alt="Result preview">${rows([['Original',(file.size/1024).toFixed(1)+' KB'],['New',(b.size/1024).toFixed(1)+' KB'],['Dimensions',w+'×'+h]])}<div class="btns"><a class="btn pri" href="${u}" download="${base}-${m==='c'?'compressed':'resized'}.${ext}">Download image</a></div>`},png?'image/png':'image/jpeg',m==='c'?f.q.value/100:.92)}catch(x){out.innerHTML=errHTML(x)}}}
function openTool(id){const t=T.find(x=>x.id===id);dlg.innerHTML=`<div class="mh"><h2>Free ${t.n}</h2><button class="x" aria-label="Close">✕</button></div><p class="mut">${t.d}</p><div id="box"></div>`;(t.custom||(b=>makeForm(t,b)))($('#box',dlg));dlg.showModal()}
dlg.onclick=e=>{if(e.target===dlg||e.target.closest('.x'))dlg.close()};
const LEGAL={'Privacy Policy':'Jadon Free Tools does not require an account and does not collect personal information. Calculators, text tools and image tools run in your browser; your files and inputs are not uploaded to our servers. Your theme choice is saved locally in your browser. Third-party services (such as a CDN or future advertising partners) may set their own cookies under their own policies.','Terms &amp; Conditions':'By using this website you agree to use the tools lawfully and at your own risk. The tools are provided “as is” without warranties. We may change or remove tools at any time.','Disclaimer':'Results are estimates for general information only and are not professional financial, legal, tax or medical advice. BMI is a basic screening measure. Please consult a qualified professional before making important decisions.','Contact':'Questions or feedback? Email contact@example.com (replace with your real address before publishing).'};
document.querySelector('footer').onclick=e=>{const h=e.target.dataset.legal;if(h){dlg.innerHTML=`<div class="mh"><h2>${h}</h2><button class="x" aria-label="Close">✕</button></div><p>${LEGAL[h]}</p>`;dlg.showModal()}};
const th=$('#theme');th.onclick=()=>{const n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;try{localStorage.setItem('jft-theme',n)}catch(e){}};
const nav=$('#nav'),mb=$('#menu');mb.onclick=()=>mb.setAttribute('aria-expanded',nav.classList.toggle('open'));nav.onclick=e=>{if(e.target.tagName==='A'){nav.classList.remove('open');mb.setAttribute('aria-expanded','false')}};
$('#yr').textContent=new Date().getFullYear();render();
